### ISSUE TITLE
to base64?

### ISSUE THREAD

**Issue by gbelmm** [fengyuanchen/compressorjs#1]
Could you export the result to base64?

**Comment by imerkle** [comment]
i third this

**Comment by tiaanduplessis** [comment]
Since a Blob object is returned, you can use [blob-to-base64](https://github.com/tiaanduplessis/blob-to-base64) on the result. @fengyuanchen  Will be happy to create the PR.

**Comment by fengyuanchen** [comment]
After got the output blob object:
```js
const reader = new FileReader();
let base64DataURL;

reader.onload = (e) => {
  base64DataURL = e.target.result;
};

reader.readAsDataURL(blob)
```

**Comment by gbelmm** [comment]
testing
