### ISSUE TITLE
image orientation?

### ISSUE THREAD

**Issue by acomito** [fengyuanchen/compressorjs#10]
Have you considered adding a check for image orientation? Or an option to leave exif data? I am doing more image work on the server with sharp, which has an autorotate feature, but the if I run the file through this on the client first, sharp will have no exif data to autorotate with. This is mostly an issue with images people upload via their iphone.

A similar package to this, `import loadImage from 'blueimp-load-image'`, has a rotate feature.

I'll look at exif-js or something else to maybe pre-pre-process it, but it'd be awesome to just pass in an extra option to image-compressor.

**Comment by 0x346e3730** [comment]
+1, portrait pictures taken on phone are rotated to landscape

**Comment by hanai** [comment]
+1, same issue

**Comment by fengyuanchen** [comment]
The new release (v0.5.0) supports to check orientation now.
