### ISSUE TITLE
Success callback is not called, no error showed, just silence

### ISSUE THREAD

**Issue by dicka88** [fengyuanchen/compressorjs#101]
My code is like this

```javascript
new Compressor(document.querySelectorAll('input[type=file]')[6].files[0], {
    quality: 0.6,
    success: function (e) {
        console.log("result", e);
    },
    error(e) {
        console.error(e);
    },
});
```
and the console log
```javascript
r {file: File, image: Image, options: {…}, aborted: false, result: null, …}
```

it like success callback is not called

And the problem because another js declare in global variable
so if you write a variable stay inside local guys :v

**Comment by dicka88** [comment]
DONE :v

**Comment by 740491** [comment]
Could you please elaborate on the solution to this problem? I am trying to pass a blob in jest but compressorjs does not output anything

**Comment by lizGarcia16** [comment]
> Could you please elaborate on the solution to this problem? I am trying to pass a blob in jest but compressorjs does not output anything

were you able to solve this?
I am doing the unit test of uploading an image and when it reaches the new Compressor part .... it does not reach the success part

**Comment by lizGarcia16** [comment]
> Could you please elaborate on the solution to this problem? I am trying to pass a blob in jest but compressorjs does not output anything

were you able to solve this?
I am doing the unit test of uploading an image and when it reaches the new Compressor part .... it does not reach the success part
