### ISSUE TITLE
Large dimensions file issue in Mozila

### ISSUE THREAD

**Issue by dilipmp** [fengyuanchen/compressorjs#102]
I have Image which has dimensions 9000 X 3000 and size is 25MB and I try to compress this image in mozila it's 
not compress proper it's getting black part on image righ side.

This same image working fine in chrome.

you can check image here 
![compressed](https://user-images.githubusercontent.com/28888542/95584523-81263a80-0a5b-11eb-86d8-104b1b508a36.jpg)

Original image
http://albumbiz.com/Orignalimage.jpg

can you please help me?

**Comment by fengyuanchen** [comment]
Avoid to get a blank output image, you might need to set the `maxWidth` and `maxHeight` options to limited numbers, because of [the size limits of a canvas element](https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element), recommend to use `4096` or lesser.
