### ISSUE TITLE
在线示例使用的jQuery的cdn被墙了，导致国内用户无法在线使用

### ISSUE THREAD

**Issue by xlzy520** [fengyuanchen/compressorjs#103]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fengyuanchen** [comment]
这个应该跟你所在的网络有关系。我的手机（联通网络）和电脑（电信网络）访问正常。
