### ISSUE TITLE
Cannot resize images 

### ISSUE THREAD

**Issue by ndanvers** [fengyuanchen/compressorjs#105]
**Describe the bug**
Attempting to downsample and resize an image returns an image that is properly downsampled - however there is no change in size

**Expected behavior**
If I pass a set of options like so
` 
               strict:true,             
               maxWidth:"2000px",
               maxHeight:"2000px",
               minWidth:"150px",
               minHeight:"150px",
`
I am expecting for my image to have its size reduced if its over 2000x2000

**Currently**
I am returned an image with the same resolution as I input

**Question**
What can I do on my end to rectify this behavior? the hosted demo doesn't seem to have this issue and works very well, I'd love to get it working like the demo. Thanks

**Desktop (please complete the following information):**
 - OS: NixOS (linux)
 - Browser Chrome

**Comment by fengyuanchen** [comment]
You may need to set the `strict` option to `false`.

**Comment by ndanvers** [comment]
Thanks for the message,

I have just attempted with strict=false and I am receiving the same results, I'll be taking a look at the native canvas.toBlob API, I just wanted to let you know that I wasn't able to resolve this issue with your suggestion.

Thanks
