### ISSUE TITLE
compressing gif properly instead of turning into a frozen frame?

### ISSUE THREAD

**Issue by archived-aft-bogus-german-visa-rejectio** [fengyuanchen/compressorjs#106]
**Is your feature request related to a problem? Please describe.**
yes. gifs are being treated as stationary images and it will only show the first frame after compression

**Describe the solution you'd like**
would be nice if we can compress gif properly instead of turning into a frozen frame

**Describe alternatives you've considered**
None-broswer approach

**Additional context**
doesn't look like there is a straighfroward way to do it in broswer

**Comment by fengyuanchen** [comment]
The Compressor.js uses the Browser's native [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API to do the compression work, which does **NOT** support multiple frames compressing.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
well it can be implemented if you animate the gif frame by frame in canvas; and then do a time-based compression or resolution-based compression but well i guess no one has time for that 

just suggesting it as an additional feature

**Comment by fengyuanchen** [comment]
It takes a lot of time to compress a frame, if there are too many frames, the compressing time will be too long, unless each frame using a separate thread (WebWorker). There are a lot of improvements that should be done in this case.

My suggestion is, if the target image is a GIF image, skip the compression work.
