### ISSUE TITLE
Cannot await the compressed result

### ISSUE THREAD

**Issue by hanoncs** [fengyuanchen/compressorjs#107]
**Describe the bug**
I need to be able to call Compressor and get the compressed image back, but since its done in the class contractor I cannot use await to wait for the compression to finish. 

I'm running a loop to shrink images until I get the desired file size, so I cannot use the success because I need to modify the compressorOptions and continue compressing. Is there no way to call the compress using await? 

How do I go about calling it like this?
![image](https://user-images.githubusercontent.com/4771689/100123683-a4505200-2e2f-11eb-8d51-9fa8eec7cd09.png)

Thanks you!

**Comment by fengyuanchen** [comment]
The `Compressor` constructor does **NOT** return a thenable object, you MUST warp it with a `Promise`:

```js
async function compress(file) {
  const result = await new Promise((resolve, reject) => {
    new Compressor(file, {
      success: resolve,
      error: reject,
    });
  });

  console.log(result);
}
```
