### ISSUE TITLE
how to get original image infomations?

### ISSUE THREAD

**Issue by warriorsworld** [fengyuanchen/compressorjs#108]
the sucess result is only about compressed file result. but i need some attributes of original image. I have to load the image once agin. How to get original infomation directly ?

**Comment by fengyuanchen** [comment]
What kind of attributes about the original image exactly? `naturalWidth/naturalHeight`?

**Comment by MattyStacks** [comment]
I think the user is requesting to carry over the exif data.

**Comment by fengyuanchen** [comment]
@Datapotomus Thanks for the hint.
@warriorsworld The Compressor only reads the Orientation information from the Exif data, for other information, you need to use other libraries to read them, such as [exifr](https://github.com/MikeKovarik/exifr).
