### ISSUE TITLE
More friendly upload backend code

### ISSUE THREAD

**Issue by weilies** [fengyuanchen/compressorjs#109]
**Is your feature request related to a problem? Please describe.**
I have a working compression code for .jpg extension.

```
    new Compressor(file, {
      quality: 0.6,
      success(result) {
        ... my upload file logic for the compressed file
     },
      error(err) {
        console.log(err.message);
      }
    });
```
But when i hit two different issues when i tried other extensions
1. .png - NO compression, original file size uploaded
2. non image extension - console error _The first argument must be an image File or Blob object._

**Describe the solution you'd like**
As described above, could same code smart enough to compress ALL image extension, and skip the compress but still proceed to the "success" section of the code and allow the upload go smoothly without another IF condition to check on the file type?

**Describe alternatives you've considered**
I am now considering write another IF to handle the upload NON-image file, which is another 10 more lines

**Comment by fengyuanchen** [comment]
1. This library is good for compressing JPEG images, but not for PNG images. If you set the `strict` option to `false`, you may find the compressed result is larger than the original one for PNG images.
2. This library is just for compressing images, but not for others, so you may have to write an extra `if` statement.
