### ISSUE TITLE
convertSize Setting is invalid

### ISSUE THREAD

**Issue by pocketChao** [fengyuanchen/compressorjs#111]
**Describe the bug**

**To Reproduce**
1. set convertSize 10000000(1M):
2.  new Compressor(imageFile, {
      checkOrientation: false,
      convertSize: 10000000,
      success: resolve,
      error: reject
    });
3. output
5. file: Blob
lastModified: 1608770800504
lastModifiedDate: Thu Dec 24 2020 08:46:40 
name: "test.jpg"
size: 1728325
type: "image/jpeg"

=>lastModified: 1608770800504
lastModifiedDate: Thu Dec 24 2020 08:46:40 
name: "test.jpg"
size: 1728325
type: "image/jpeg"
__proto__: Blob

**Expected behavior**

**Screenshots**

all device

**Comment by fengyuanchen** [comment]
What's the error exactly?
