### ISSUE TITLE
Add "maxSize" in option to determine the maximum image size after compress

### ISSUE THREAD

**Issue by nguyenngo99** [fengyuanchen/compressorjs#112]
My backend limit upload size to 500kb. So an option to limit filesize after compress would be helpful. Thank you.

**Comment by fengyuanchen** [comment]
It is easy to check the file size before upload in a few codes, so I think this option is not necessary.

> It is more important to keep this lib simple and small.

**Comment by avshyz** [comment]
While checking the file size before upload is straightforward, it doesn’t address the core issue. 

Without a built-in option to limit the output file size, users have to implement a trial-and-error loop, repeatedly compressing until the result falls within the size limit. This approach can be inefficient and significantly increase processing time. An option to set a maximum file size directly within the library would streamline this process and be beneficial to many developers with file size restrictions, like those implementing a 500KB limit.

**Comment by corradopetrelli** [comment]
I think like @avshyz
