### ISSUE TITLE
Compressor returns null

### ISSUE THREAD

**Issue by michaelhla** [fengyuanchen/compressorjs#114]
**Describe the bug**
Compressor returns null despite valid file input 
**To Reproduce**
```js
imgcompress(files) {  // *** for some reason, compressor returns null ***
  console.log('input', files)
  var compressedFiles = []
  files.forEach(file => {
    new Compressor(file, { 
      quality: 0.9, 
      maxHeight: 100, 
      maxWidth: 150, 
      success(result){ 
        compressedFiles = compressedFiles.push(result)
      }
    })
  })
  console.log('compFiles', compressedFiles)
  return compressedFiles
}
```
**Expected behavior**
return a compressed file 
**Screenshots**

**Desktop (please complete the following information):**

MacOS 10.15.7
Chrome latest version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fengyuanchen** [comment]
The compressing process is **asynchronous**!.

**Comment by fengyuanchen** [comment]
Use `async/await` or `Promise` to resolve the asynchronous job!
