### ISSUE TITLE
Support for HEIC

### ISSUE THREAD

**Issue by mesqueeb** [fengyuanchen/compressorjs#116]
On the website I can't seem to drag and drop .HEIC images (from iPhone camera roll)

Is this library supported when a user uploads an image via iPhone camera roll? (therefore the image is probably HEIC)

<img width="846" alt="image" src="https://user-images.githubusercontent.com/3253920/107728286-03d44480-6d31-11eb-99a0-47213e0e5c96.png">

**Comment by fengyuanchen** [comment]
This is not a problem with Compressor.js, but your operating system or browser!

**Comment by fengyuanchen** [comment]
Please check out if your operating system or browser supports HEIC files.

**Comment by mesqueeb** [comment]
Yes, it's Safari browser and macOS operating system. Both Apple products :)

**Comment by umihui** [comment]
I have run into the same issue with Safari browser. The weird part is that it said 'Failed to load the image', but the input image section got the information.
<img width="746" alt="Screen Shot 2021-03-02 at 11 57 22 AM" src="https://user-images.githubusercontent.com/6075741/109706978-783f1e00-7b4e-11eb-823a-ac5ede12d957.png">

**Comment by Andrew-Chen-Wang** [comment]
This is interesting because the mime type is actually image/gif, which this library doesn't support...

**Comment by fengyuanchen** [comment]
Actually, there are no browsers that support HEIC images currently.

> Browser compatibility: https://caniuse.com/heif

**Comment by Andrew-Chen-Wang** [comment]
Hm I wonder why compressor.js converted my heic to image/gif. Either way, gifs aren't supported here either so oh well. @umihui There is a JS library for converting HEICs to gif, jpg, and png if you're interested.

**Comment by jtreitz** [comment]
this issue is pinned but it's not obvious to me what the current state of HEIC in this lib is
