### ISSUE TITLE
PNG quality getting affected

### ISSUE THREAD

**Issue by zehawki** [fengyuanchen/compressorjs#118]
**Describe the bug**
According to my understanding png files smaller than convertSize and maxHeight/maxHeight will not be touched in any way. However I can clearly see that logos (small pngs, with transparency + text are affected quite badly), and there is a distinct loss in quality & sharpness.

**To Reproduce**
1. Go to https://fengyuanchen.github.io/compressorjs/. No setting needs be changed
2. Use https://ibb.co/6XRQJkm
3. Compare left right

**Expected behavior**
No loss of fidelity in the returned image

**Comment by fengyuanchen** [comment]
Actually, there are the same images on the left and right sides, but there are overlapped on the left side, as there are transparent PNG images, you will feel like the left side is more high-quality.

Exactly, it is a bug of the image comparing component, just add `background-color: white` style to the left `<img>` element, and you will find that there are the same in visual totally.
