### ISSUE TITLE
`this.image` is probably not used

### ISSUE THREAD

**Issue by tedmx** [fengyuanchen/compressorjs#121]
Is `this.image` a "dead" field?
https://github.com/fengyuanchen/compressorjs/blob/master/src/index.js#L33

The only usage of it, as I see now, is in `abort` method here: https://github.com/fengyuanchen/compressorjs/blob/master/src/index.js#L336.

**Comment by fengyuanchen** [comment]
There are many `const { image } = this` fragments in the source code.
