### ISSUE TITLE
Image corruption 

### ISSUE THREAD

**Issue by SpazzRabbit** [fengyuanchen/compressorjs#122]
Browser: Tor Browser last ver.
I think this is caused by the "Blocked error https://fengyuanchen.github.io/compressorjs/ from extracting canvas data because no user input was detected."
![image](https://user-images.githubusercontent.com/62895104/114159027-8d7a4a00-994f-11eb-8c83-3e73a249bbf5.png)

How to make convert by user input?

**Comment by fengyuanchen** [comment]
The Compressor.js may not work in the Tor browser.

**Comment by SpazzRabbit** [comment]
@fengyuanchen 
I think this is not a browser specific issue, it is a problem with disabling trackers that use canvas. For Compressor.js to work, you need a user input. I have not yet been able to call the work through the user input so that everything works

**Comment by VityaSchel** [comment]
I added canvas data extraction block detection to my app using this snippet:
```js
document
    .createElement('canvas')
    .getContext('2d')
    ?.getImageData(0, 0, 1, 1)
    .data.every((v) => v === 0)
```
This creates a blank virtual canvas without appending it to DOM, immediately extracts data and checks whether it's still blank or filled with random data.
Tested in Tor browser, Firefox, Chrome and Safari.
