### ISSUE TITLE
convertSize to webp as an option

### ISSUE THREAD

**Issue by zehawki** [fengyuanchen/compressorjs#123]
**Is your feature request related to a problem? Please describe.**
Current behavior - PNG files over convertSize value will be converted to JPEGs (https://github.com/fengyuanchen/compressorjs#convertsize)

**Describe the solution you'd like**
Suggested enhancement - Add a feature (and flag) which will convert PNGs to WEBP instead of JPEG.

**Additional context**
This is to retain PNG transparency while reducing the image size

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, I will think about it.
