### ISSUE TITLE
上传图片前使用 compressorjs 压缩，发现图片变黑了

### ISSUE THREAD

**Issue by liuxsen** [fengyuanchen/compressorjs#124]
**Describe the bug**
上传图片前使用 compressorjs 压缩，发现图片变黑了

![image](https://user-images.githubusercontent.com/12598696/119786621-f4a18d00-bf02-11eb-9235-460745b486ec.png)
![image](https://user-images.githubusercontent.com/12598696/119786666-fff4b880-bf02-11eb-9792-603c8d356d99.png)

调用方式：

![image](https://user-images.githubusercontent.com/12598696/119786797-1f8be100-bf03-11eb-89f8-a7e11cf865b0.png)
![image](https://user-images.githubusercontent.com/12598696/119786843-29154900-bf03-11eb-9bc6-fbfbbde3fe05.png)

**Comment by fengyuanchen** [comment]
可能有最大内存限制，建议设置 `maxWidth` 和 `maxHeight` 参数：

```js
new Compressor(file, {
  maxWidth: 4096,
  maxHeight: 4096,
});
```

**Comment by liuxsen** [comment]
> 可能有最大内存限制，建议设置 `maxWidth` 和 `maxHeight` 参数：
> 
> ```js
> new Compressor(file, {
>   maxWidth: 4096,
>   maxHeight: 4096,
> });
> ```
我尝试过了，但是没有效果； 又出现了如下的图片；

![image](https://user-images.githubusercontent.com/12598696/123943177-771fdf80-d9ce-11eb-85fa-9de069dd5245.png)

**Comment by liuxsen** [comment]
> 可能有最大内存限制，建议设置 `maxWidth` 和 `maxHeight` 参数：
> 
> ```js
> new Compressor(file, {
>   maxWidth: 4096,
>   maxHeight: 4096,
> });
> ```

我直接设置width: 1200px 会不会有效果呢

**Comment by houzhichaoLove** [comment]
> > 可能有最大内存限制，建议设置 `maxWidth` 和 `maxHeight` 参数：
> > ```js
> > new Compressor(file, {
> >   maxWidth: 4096,
> >   maxHeight: 4096,
> > });
> > ```
> 
> 我直接设置width: 1200px 会不会有效果呢

请问解决了吗, 最后?

**Comment by liuxsen** [comment]
> > > 可能有最大内存限制，建议设置 `maxWidth` 和 `maxHeight` 参数：
> > > ```js
> > > new Compressor(file, {
> > >   maxWidth: 4096,
> > >   maxHeight: 4096,
> > > });
> > > ```
> > 
> > 
> > 我直接设置width: 1200px 会不会有效果呢
> 
> 请问解决了吗, 最后?

不知道呢，我昨天刚上线，看还会不会出现问题，关键我让客户重新上传的时候，竟然没有重现，后台看审计日志，发现确实有时候重新上传就可以了， 所以我不知道是我们前端包的问题还是后端保存时候的问题。因为业务原因没有直接上传oss
