### ISSUE TITLE
Is there a way to handle up to 1000 images in iOS safari?

### ISSUE THREAD

**Issue by warrenkc** [fengyuanchen/compressorjs#125]
I have run into an issue where about 150 images seems to crash the browser in iOS.
Is there something I am doing wrong? Thank you so much for your help.

Here is my sample code: https://codepen.io/warrenkc/pen/vYxdXzr

**Comment by fengyuanchen** [comment]
Don't compress all the images at the same time, which will crash the browser absolutely. You may have to compress the images one by one, man!

**Comment by warrenkc** [comment]
Hi. I know that. I do them one by one and it still crashes. You can see here: https://codepen.io/warrenkc/full/RwpMMVP

**Comment by fengyuanchen** [comment]
Just check out your code, the compressing tasks are still parallel, but not a chain!

**Comment by fengyuanchen** [comment]
The real example for one by one:

```js
async function compress(files) {
  for (const file of files) {
    await new Promise((resolve, reject) => {
      new Compressor(file, {
        success: resolve,
        error: reject,
      });
    });
  }
}

compress(files).then((result) => {
  console.log('Compress success');
}).catch((err) => {
  console.log('Compress error');
}).finally(() => {
  console.log('Compress complete');
});
```

**Comment by warrenkc** [comment]
You are awesome! Thank you.
