### ISSUE TITLE
Progressive JPEG

### ISSUE THREAD

**Issue by wpsumo** [fengyuanchen/compressorjs#126]
**Is your feature request related to a problem? Please describe.**
Does not make jpg images Progressive

**Describe the solution you'd like**
Convert and compress to progressive jpeg.

**Additional context**
Would also be preferred if we could have a solution to convert .jpeg to .jpg if needed to keep optimizations clean.

**Comment by fengyuanchen** [comment]
[What is Progressive JPEG?](https://whatis.techtarget.com/search/query?q=What+is+Progressive+JPEG)

**Comment by fengyuanchen** [comment]
This library uses the Browser's native canvas.toBlob API to do the compression work, which means it is lossy compression, asynchronous, and not support Progressive JPEG.
