### ISSUE TITLE
There is no effect in using Canvas's DrawImage method in Hook Function Drew.

### ISSUE THREAD

**Issue by zclzone** [fengyuanchen/compressorjs#127]

**Comment by fengyuanchen** [comment]
Follow this example: https://fengyuanchen.github.io/compressorjs/examples/watermark.html

**Comment by zclzone** [comment]
Thank you for your reply, i mean the drawImage method, instead of fillText, fillText is OK.

**Comment by zclzone** [comment]
> Follow this example: https://fengyuanchen.github.io/compressorjs/examples/watermark.html

Thank you for your reply, i mean the drawImage method, instead of fillText, fillText is OK.

**Comment by zclzone** [comment]
> Follow this example: https://fengyuanchen.github.io/compressorjs/examples/watermark.html

Sorry, I tried again and found that there was no problem, Thank you very much.

**Comment by xcellenceit** [comment]
I am trying to add picture watermark using DrawImage but unable to make it work. Can you pls share how you did that?
