### ISSUE TITLE
Feature request - give heavier tasks a separate thread

### ISSUE THREAD

**Issue by Verdidk** [fengyuanchen/compressorjs#13]
First of all great job on creating this image-compressor, I love it!

I was wondering if it could be made even more efficient by putting the heavier tasks of compressing an image in a separate thread (for example with webworkers, though this example can be a lot of work with workers having no access to the DOM).

The reason for this idea is that when using this compressor in a web based application I noticed that the page freezes temporarily when processing an image on a phone and with very large images even a computer can freeze for a few seconds. 

I hope this is an idea interesting enough to be worth pursuing!

**Comment by fengyuanchen** [comment]
May not be able to support this as the core compression work of this library is did by the [`canvas.toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API which requires DOM (`<canvas>`).

**Comment by cjz9032** [comment]
> May not be able to support this as the core compression work of this library is did by the [`canvas.toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API which requires DOM (`<canvas>`).

nowdays canvas is supported

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers#:~:text=Broadcast%20Channel%20API-,Canvas%20API,-Channel%20Messaging%20API
