### ISSUE TITLE
Enforce image dimensions

### ISSUE THREAD

**Issue by AbrahemAlhofe** [fengyuanchen/compressorjs#130]
**Is your feature request related to a problem? Please describe.**
When I set `height` and `width` options I want the output image dimensions to be like what I wanted, so it is not logical to follow the aspect ratio when I set both dimensions explicitly

**Describe the solution you'd like**
Enforce image dimensions with my expectation when both `height` and `width` options are set explicitly

**Comment by andrewspy** [comment]
I presume the image would also be center crop when both `height` and `width` options are set explicitly?
