### ISSUE TITLE
Same quality number vastly different filesizes based on browser

### ISSUE THREAD

**Issue by sarunluitel** [fengyuanchen/compressorjs#132]
Compressed Image size is vastly different on different browsers. 

Used a jpg Image, Original Filesize 12.1 MB (8192x4159) on the online compressor tool. 
Image Link : https://images.pexels.com/photos/1519753/pexels-photo-1519753.jpeg

used settings: 
maxWidth => 2048 
quality => 0.5
rest => defaults

Results are as follows: (Test run on 2015 Macbook Air)
Safari 13.1.2 => 807 KB
Chrome 93.0 =>434 KB
Firefox 92.0 =>  498 KB

(Test run on ipad)
Safari (ipados 14.7.1) => 641KB
Chrome 93.0 =>641 KB
(loaner Ipad did not have password to install firefox)

(Test run on Ubuntu 20.04)
chrome 93 =>434KB
Firefox 93=> 498KB
Edge Beta 94 => 434KB
Brave (chromium 93) =>352KB

(Test run on WIndows 10) => (same result on android 10)
Brave (chromium 93) =>434KB
Chrome 93=> 434KB
Edge => 434 KB
Firefox 93=> 498KB

If this is a know issue is there an equivalency factor between the browsers? for the Image I was testing putting quality 0.3 on macbook safari gives 420KB. is it advisable to set the quality dynamically based on user's browser and OS?

**Comment by fengyuanchen** [comment]
This is a known issue! 

Why? The Compressor uses the Browser's native [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API to do the compression work, but different browsers have different implementations of the `canvas.toBlob` API.
