### ISSUE TITLE
Use convertSize for webp images as well

### ISSUE THREAD

**Issue by zehawki** [fengyuanchen/compressorjs#133]
**Is your feature request related to a problem? Please describe.**
Current behavior - PNG files over convertSize value will be converted to JPEGs (https://github.com/fengyuanchen/compressorjs#convertsize)

**Describe the solution you'd like**
Suggested enhancement - Like PNGs, convert WEBP over convertSize into JPEG.

**Additional context**
This is to have the same behavior between both images types and maintain control over final image size

**Comment by fengyuanchen** [comment]
You can try to set the `mimeType` option to `image/jpeg` currently.

**Comment by fengyuanchen** [comment]
See #123.

**Comment by zehawki** [comment]
On subsequent thought, I realized that what I asked for is kind of meaningless since webp anyway results in far better compression/size vs jpeg, and with idiotic safari also finally supporting, there is no reason not to use webp...
