### ISSUE TITLE
Does not resize PNG image as expected under certain conditions

### ISSUE THREAD

**Issue by zehawki** [fengyuanchen/compressorjs#134]
**Describe the bug**
Does not resize an image

**To Reproduce**
1. Go to https://fengyuanchen.github.io/compressorjs/
2. Use the image from https://www.transparentpng.com/download/happy-st-patricks-day-_34433.html
3. Set maxWidth to 1035px or higher
4. Image wont resize

**Expected behavior**
Should resize to 1035px or higher

**Screenshots**
![image](https://user-images.githubusercontent.com/8095144/132956388-9ece7771-98a9-4e5a-8a13-6980caebfd77.png)

**Additional context**
Any maxWidth < 1035px correctly resizes the image.

This same kind of behavior is seen with different images, with different values of maxWidth. This library is unexpectedly buggy.

**Comment by fengyuanchen** [comment]
Why not use the `minWidth` option?

**Comment by fengyuanchen** [comment]
For your case, you may need to set the [`strict`](https://github.com/fengyuanchen/compressorjs#strict) option to `false`.

**Comment by zehawki** [comment]
Nope, there is something really wrong here. I'm trying with another PNG image that is ~3000 x 4000 px. Asking for maxWidth = 2500 blows up the image size massively.

![image](https://user-images.githubusercontent.com/8095144/133984902-3cbd5d25-eddd-4f83-b449-7a239b4dc44d.png)

**Comment by fengyuanchen** [comment]
This is why the `strict` option should be set to `true` by default, as it is hard to compress PNG images.

**Comment by fengyuanchen** [comment]
For compressing PNG images:

- Set the `mimeType` option to `image/jpeg`.
- Or set the `convertSize` option to a small value.
