### ISSUE TITLE
Can it be use in react native?

### ISSUE THREAD

**Issue by hayr-hotoca** [fengyuanchen/compressorjs#136]
**Is your feature request related to a problem? Please describe.**
I want to use it in react native

**Comment by fengyuanchen** [comment]
Yes. This is a pure JavaScript library.

**Comment by fengyuanchen** [comment]
I'm not sure, maybe you can give it a try.

**Comment by mustafaskyer** [comment]
hey @lincdh , any feedback about your try ?

**Comment by mgav** [comment]
Hey @lincdh, Check out https://www.npmjs.com/package/react-image-file-resizer

**Comment by ashokkumar88** [comment]
@lincdh Did it work for you for react-native?

**Comment by fengyuanchen** [comment]
May not support to use this library in React Native.
