### ISSUE TITLE
I got this error in compilation time (UnhandledPromiseRejectionWarning: ReferenceError: window is not defined)

### ISSUE THREAD

**Issue by amirhoseinsalehi** [fengyuanchen/compressorjs#137]
In the latest release of compressorJs, I got this error in compilation time:

`(node:150) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined at /builds/dropp-front-end/webapp/node_modules/compressorjs/dist/compressor.common.js:229:6 `

so I revert the version in the package.json to the latest stable version and it worked.
please mind this error in the latest release which is on October 1.

**Comment by besnikh** [comment]
I have the same error

iI am using nuxtjs and it was working with version 1.0.7 but after upgrade it stopped working
