### ISSUE TITLE
Can't find variable: Image at node_modules/compressorjs/dist/compressor.js:696:10 in init

### ISSUE THREAD

**Issue by oussamabenkortbi** [fengyuanchen/compressorjs#139]
**Describe the bug**
Can't find variable: Image
at node_modules/compressorjs/dist/compressor.js:696:10 in init

React Native using expo
i passed a blob as following:
![Screenshot from 2021-10-11 11-03-21](https://user-images.githubusercontent.com/34894866/136772224-73e1b641-98cd-4989-b927-5d6f5a565788.png)

**Comment by fengyuanchen** [comment]
May not support to use this library in React Native.
