### ISSUE TITLE
Is there any way to preserve the image transparency?

### ISSUE THREAD

**Issue by Saikedo** [fengyuanchen/compressorjs#140]
Is there a way to indicate the image output format? I would like to specify the output as a .png or .webp or something like that and also preserve the transparency layer of the image.

Thank you.

**Comment by nickscamara** [comment]
Same issue here after updating it.

**Comment by nickscamara** [comment]
Quick update: after some digging, it seems to have something to do with the image properties. I uploaded another screenshot (png) that had a transparent background and it worked. Same properties but generated by 2 different softwares.

**Comment by nickscamara** [comment]
After more research, it seems that if the PNG exceeds 5MB it converts to a jpeg, removing the transparency. I discovered this the hard way. After a couple of minutes, I saw that this is specified in the documentation on the convertSize part. I would personally make that more explicit in the documentation, if possible :)

**Comment by fengyuanchen** [comment]
1. Set the [convertTypes](https://github.com/fengyuanchen/compressorjs#converttypes) option to `[]` or `''`.
2. Or set the [convertSize](https://github.com/fengyuanchen/compressorjs#convertsize) option to `Infinity`.

**Comment by Saikedo** [comment]
@fengyuanchen The issue with that is that it will almost stop compresssing the image.

I tried uploading a 8.42 MB png image with converTypes set to `[]` or to` ['image/webp']` and it only compresses it down to 8.07 MB. I tried multiple other conversion methods and they were able to compress this down to less than 1MB while also preserving the transparency.

**Comment by fengyuanchen** [comment]
@Saikedo This is a simple & light compressor, which uses the Browser's native `canvas.toBlob` API to do the compression work, which means it is not changeable and has different compression effects in different browsers.

For higher requirements, I will suggest to use other solutions, such as: https://tinypng.com/
