### ISSUE TITLE
it Not work in Safari, I Tryit with two mobile phones

### ISSUE THREAD

**Issue by plas007** [fengyuanchen/compressorjs#142]
When I choose a picture greater than 6MB, it doesn't work.It outputs a File, However, it is actually output a Blob when it works.
I use it int uniapp for H5.
When it work in windows or Android it works well. when the pictrue smaller than 6MB it also works well.
I can't find the reason for this, can someone help me?

**Comment by fengyuanchen** [comment]
For a huge image, you may need to set the `checkOrientation` option to `false`, or set the `maxWidth` option to a small number.

References:
- https://github.com/fengyuanchen/compressorjs#checkorientation
- https://github.com/fengyuanchen/compressorjs#maxwidth
