### ISSUE TITLE
压缩后大小并未变化

### ISSUE THREAD

**Issue by 3261564019** [fengyuanchen/compressorjs#143]
压缩后大小并未变化

![image](https://user-images.githubusercontent.com/70420794/155082184-7067c47c-e617-438b-9bc7-a46447162299.png)
![image](https://user-images.githubusercontent.com/70420794/155082239-5de5544a-a5fa-447d-81ee-1ceb80a56081.png)

**Comment by fengyuanchen** [comment]
这是因为跳过压缩了（因为压缩后到文件反而比原文件大）。如果不介意文件大小变大的话，可以将 `strict` 参数设置为 `false`。
