### ISSUE TITLE
图片大小1.2M，压缩没效果，还是这个大小，是使用有问题吗？

### ISSUE THREAD

**Issue by xiandanchaorenguagua** [fengyuanchen/compressorjs#148]
`<script setup lang="ts">
import { ref } from 'vue'
import Compressor from 'compressorjs';

let fileList = ref([])

const beforeRead = (file:any) =>
    new Promise((resolve) => {
        new Compressor(file, {
            success: resolve,
            error(err) {
                console.log(err.message);
            },
        });
    });

let aftereUpload = (file:any, details:any) =>{
    console.log(file)
}

</script>

<template>
    <div class="image-manage content-container">
        <van-uploader v-model="fileList" :before-read="beforeRead" :after-read="aftereUpload" upload-icon="plus" accept="image/*"/>
    </div>
</template>

<style rel="stylesheet/scss" lang="scss" scoped>
</style>`

**Comment by fengyuanchen** [comment]
See the [`strict`](https://github.com/fengyuanchen/compressorjs#strict) option for details.
