### ISSUE TITLE
Blurring/low quality resizing

### ISSUE THREAD

**Issue by HappyCatKitten** [fengyuanchen/compressorjs#154]
**Describe the bug**
Bad quality when resizing

**To Reproduce**
I have a simple async call to the compressor like so:

```
`function compressAsync(file, maxWidth, maxHeight, quality) {
    return new Promise((resolve, reject) => {
        new Compressor(file, {
            quality: quality,
            maxWidth:maxWidth,
            maxHeight:maxHeight,
            mimeType:'image/webp',
            success(result) {
                resolve(result)
            },
            error(e) {
                reject(e)
            },
        });
    })
}`
```

Compressing the image with no resize produces great results, however resizing seems to destroy the quality. 

My example uses webp however I have tried png and jpeg with quality all the way up to 0.95

**outputs**

No resize, just convert to webp (looks great)

![image](https://user-images.githubusercontent.com/1046264/172107439-64ffa877-c31a-4d21-9fe3-94c654f01fa8.png)

downsize to 1024x1024 - text in top left and the quality of the "bubble" around the helmet. 

![image](https://user-images.githubusercontent.com/1046264/172107619-508f4aff-9c35-4771-8405-52f06b18abf9.png)

downsize to 640x640 - also color degredation (seems washed)

![image](https://user-images.githubusercontent.com/1046264/172107743-84754863-c99c-4855-93f5-774c2327d5e7.png)

downsize to 320x320

![image](https://user-images.githubusercontent.com/1046264/172107895-cea74736-9320-4810-9dbf-9a9e772c08c1.png)

**Running on**
Ubuntu 22.0
Brave & Firefox latest

Notes:

I have tried on a number of images with the same results

**Comment by fengyuanchen** [comment]
The Compressor.js uses the Browser's native [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API to do the compression work, which means it is **lossy compression**, asynchronous, and has **different compression effects in different browsers**.

**Comment by fengyuanchen** [comment]
So, you may need another library to do the compression work for better quality.
