### ISSUE TITLE
Only compress resized images

### ISSUE THREAD

**Issue by mjau-mjau** [fengyuanchen/compressorjs#157]
This seems like an obvious missing feature. Say you have an uploader, and want to limit width/height to max 1600 px. Images that need to be resized, will get re-compressed obviously ... However, small images that don't need resizing will also get re-compressed, even when they don't resize. This seems useless.

Basically, if an uploader has option `[x] Resize 2000 x 2000`, it would need to have some helper text `When enabled, this option will also re-compress smaller images that don't get resized`. Its virtually impossible to use Compressor.js to only resize images that are beyond certain dimensions, without also re-compressing smaller images. Surely some missing logic to make it useful?

**Comment by fengyuanchen** [comment]
This is an image compressor, which means it **compresses** any images passed in. Furthermore, the `width` or `height` options are **optional**.

**Comment by mjau-mjau** [comment]
True. But surely the point of the various `width` and `height` options are to be able to resize images, what else is the point? ... For any practical usage of resize, one would want to compress only images that require resizing. For instance, https://github.com/transloadit/uppy uses Compressor.js, and the resize feature is tremendously useful, except it's rendered kinda useless because it also forces re-compression on images that don't require resizing. Not your task of course, but worth mentioning. Thanks for the script.
