### ISSUE TITLE
How to get compressed base64 from result

### ISSUE THREAD

**Issue by Rajdeepc** [fengyuanchen/compressorjs#158]
@fengyuanchen 

I am trying to create a base64 reader from the success hook but I am always getting a blob from the result. I am able to convert the blob to base64 but it is not compressed one.
Is there any way I can get the compressed base64 from the result?

When i do this
```
 const compressedImage = await new Compressor(e.target.files[0], { quality: 0.6 });
    console.log(compressedImage)

```

I am getting the below result with reader as null
<img width="810" alt="Screenshot 2022-08-19 at 4 30 34 PM" src="https://user-images.githubusercontent.com/8790510/185604761-15131894-bec5-4e31-ae4b-b7efb8e02c0c.png">

**Comment by fengyuanchen** [comment]
See this: [Convert blob to base64](https://stackoverflow.com/questions/18650168/convert-blob-to-base64).
