### ISSUE TITLE
Image is not compressed 

### ISSUE THREAD

**Issue by rameezraja2755** [fengyuanchen/compressorjs#161]
**Describe the bug**
i am trying to compress image with following code but size of compressed image is same as the original image 

 new Compressor(fileUploaded, {
      quality: 0.6,
      success: (compressedResult) => {
        console.log("compressed image size", compressedResult.size / 1000000);
        console.log("real image size", fileUploaded.size / 1000000);
      },
    });

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser chrome
 - Version 105.0.5195.102 (Official Build) (x86_64)

**Comment by fengyuanchen** [comment]
Checkout the following 3 options first: [`strict`](https://github.com/fengyuanchen/compressorjs#strict), [`convertTypes `](https://github.com/fengyuanchen/compressorjs#converttypes), and [`convertSize `](https://github.com/fengyuanchen/compressorjs#convertsize).
