### ISSUE TITLE
initialWidthInPx and initialHeightInPx don't work

### ISSUE THREAD

**Issue by alexolliveira** [fengyuanchen/compressorjs#163]
I've tried it: alert(initialWidthInPx+"x"+initialHeightInPx ); In this case, it is working well. result: 800x800.
This way is working too: 
if(initialWidthInPx<800){
}
But when I try like this:
if(initialWidthInPx<800 && initialHeightInPx<800 ){
}
it doesnt work.

Any idea?

**Comment by fengyuanchen** [comment]
Try `if (initialWidthInPx < 800 || initialHeightInPx < 800 ) { ... }`?

**Comment by alexolliveira** [comment]
It worked! Thanks bro!
