### ISSUE TITLE
Error with dynamic import()

### ISSUE THREAD

**Issue by andrewspy** [fengyuanchen/compressorjs#164]
**Describe the bug**
`Compressor` class is not defined when dynamic import as follow:

```js
// import Compressor from 'compressorjs' // static import works fine
const { default: Compressor } = await import('compressorjs')

new Compressor(file)
```
console error:
```
Uncaught (in promise) ReferenceError: Compressor is not defined
```

**To Reproduce**
1. Use the snippet above.
2. See the error in the console log.

**Expected behavior**
Dynamic import should work accordingly.

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version:  107

**Additional context**
Typescript seems to detect the types correctly but does not work at runtime.

**Comment by fengyuanchen** [comment]
Cannot be reproduced. Please check your bundler configuration.

**Comment by fengyuanchen** [comment]
Cannot be reproduced. Please check your bundler configuration.

**Comment by andrewspy** [comment]
I found the bug in my own code, which has nothing to do with the bundler. Sorry for the trouble.
