### ISSUE TITLE
Pictures of any size have not changed in Safari

### ISSUE THREAD

**Issue by Tithy** [fengyuanchen/compressorjs#166]
ios 15.5

**Comment by Tithy** [comment]
https://fengyuanchen.github.io/compressorjs/
Select any image, change the quality, the image size has not changed, not on Android and PC.
The parameters I introduced when testing are quality: 0.6，strict：false，It did not work as expected。
Subsequently, when I tested it using the official website, I also got consistent results in Safari. Images of any size get results after changing the quality and the original image has not been changed.

ps: Forgive the bad English and use translation software.

**Comment by fengyuanchen** [comment]
Cannot reappear. 

Try this:

1. Set the `strict` option to `false`.
2. Set the `quality ` option to `0.1`.

**Comment by Tithy** [comment]
Sorry I tested some photos that did work, I tested 20Mb and 5Mb or so images just didn't change, you can try this image, according to your settings and did not send changes.
![微信图片_20221127165204](https://user-images.githubusercontent.com/28753993/204135278-af0bbb8a-6d9c-4b50-977b-adf0b0e37882.jpg)

**Comment by Tithy** [comment]
This may be related to the fact that the canvas area in iOS memory exceeds the maximum limit, and there is no solution for the time being

**Comment by Klaasvaak** [comment]
Wouldn't it be possible to use [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/Window/createImageBitmap) with the `resizeWidth` and `resizeHeight` for these cases?

I know that using `createImageBitmap` can cause some other issues with compatibility though.
