### ISSUE TITLE
retainExif will prevent loading of png image

### ISSUE THREAD

**Issue by foochifa** [fengyuanchen/compressorjs#168]
**Describe the bug**
When the retainExif option is enabled, trying to compress a png image will result in a 'Failed to load the image' error. 

**To Reproduce**
Compress a Png image with the retainExif option set to True

**Expected behavior**
Png should be loaded and compressed. 

**Screenshots**
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/59867455/220261939-dbc61812-19fb-43ab-a0e4-616660622427.png">

**Comment by foochifa** [comment]
Perhaps could limit the retainExif option to jpeg only, like checkOrientation.

Could I also suggest potentially using external exif reader packages to extract the exif data like [exif-js](https://github.com/exif-js/exif-js) or [exifreader](https://github.com/mattiasw/ExifReader)

**Comment by fengyuanchen** [comment]
Got it, I will limit the `retainExif` option to JPEG images only.

**Comment by fengyuanchen** [comment]
See #169.
