### ISSUE TITLE
[Error]Safari: The operation is insecure.

### ISSUE THREAD

**Issue by lcw0622** [fengyuanchen/compressorjs#17]
Thanks for xkeshi, this tool works well on chrome, but in safari   throws an  error on this line:
canvas.toBlob(resolve, options.mimeType, options.quality);

anyone has any idea about this ? Here is my code:
```javascript
const file = (<HTMLInputElement>document.getElementById('pic' + target)).files[0];
const compress = new ImageCompressor(file, {
        convertSize: 1000000,
        maxWidth   : 768,
        maxHeight  : 768,});
```

**Comment by lihongqiang123** [comment]
My compressed image on the ios phone also failed. Who knows?

**Comment by fengyuanchen** [comment]
What is the OS version and Safari version?
