### ISSUE TITLE
Failed to load the image

### ISSUE THREAD

**Issue by vijay-growmax** [fengyuanchen/compressorjs#171]
**Describe the bug**
columnNumber: 23
fileName: "http://localhost:3000/static/js/vendors-node_modules_compressorjs_dist_compressor_js-node_modules_lodash_uniqueId_js.chunk.js"
lineNumber: 892
message: "Failed to load the image."
stack: "./node_modules/compressorjs/dist/compressor.js/</load/image.onerror@http://localhost:3000/static/js/vendors-node_modules_compressorjs_dist_compressor_js-node_modules_lodash_uniqueId_js.chunk.js:892:23\nEventHandlerNonNull*load@http://localhost:3000/static/js/vendors-node_modules_compressorjs_dist_compressor_js-node_modules_lodash_uniqueId_js.chunk.js:891:9\ninit@http://localhost:3000/static/js/vendors-node_modules_compressorjs_dist_compressor_js-node_modules_lodash_uniqueId_js.chunk.js:812:16\nCompressor@http://localhost:3000/static/js/vendors-node_modules_compressorjs_dist_compressor_js-node_modules_lodash_uniqueId_js.chunk.js:774:12\nhandleUpload@http://localhost:3000/static/js/src_Mobile_DashboardPages_Accounts_AccountsLanding_js.chunk.js:348:7\ncallCallback@http://localhost:3000/static/js/bundle.js:123853:18\ninvokeGuardedCallbackDev@http://localhost:3000/static/js/bundle.js:123902:20\ninvokeGuardedCallback@http://localhost:3000/static/js/bundle.js:123962:35\ninvokeGuardedCallbackAndCatchFirstError@http://localhost:3000/static/js/bundle.js:123977:29\nexecuteDispatch@http://localhost:3000/static/js/bundle.js:128212:46\nprocessDispatchQueueItemsInOrder@http://localhost:3000/static/js/bundle.js:128244:26\nprocessDispatchQueue@http://localhost:3000/static/js/bundle.js:128257:41\ndispatchEventsForPlugins@http://localhost:3000/static/js/bundle.js:128268:27\ndispatchEventForPluginEventSystem/<@http://localhost:3000/static/js/bundle.js:128479:16\nbatchedEventUpdates$1@http://localhost:3000/static/js/bundle.js:142164:16\nbatchedEventUpdates@http://localhost:3000/static/js/bundle.js:123651:16\ndispatchEventForPluginEventSystem@http://localhost:3000/static/js/bundle.js:128478:26\nattemptToDispatchEvent@http://localhost:3000/static/js/bundle.js:125961:40\ndispatchEvent@http://localhost:3000/static/js/bundle.js:125879:45\nunstable_runWithPriority@http://localhost:3000/static/js/bundle.js:264607:16\nrunWithPriority$1@http://localhost:3000/static/js/bundle.js:131259:14\ndiscreteUpdates$1@http://localhost:3000/static/js/bundle.js:142181:18\ndiscreteUpdates@http://localhost:3000/static/js/bundle.js:123663:16\ndispatchDiscreteEvent@http://localhost:3000/static/js/bundle.js:125845:22\nEventListener.handleEvent*addEventBubbleListener@http://localhost:3000/static/js/bundle.js:125967:14\naddTrappedEventListener@http://localhost:3000/static/js/bundle.js:128382:33\nlistenToNativeEvent@http://localhost:3000/static/js/bundle.js:128346:32\nlistenToAllSupportedEvents/<@http://localhost:3000/static/js/bundle.js:128297:32\nlistenToAllSupportedEvents@http://localhost:3000/static/js/bundle.js:128295:25\npreparePortalMount@http://localhost:3000/static/js/bundle.js:130546:35\ncompleteWork@http://localhost:3000/static/js/bundle.js:139406:31\ncompleteUnitOfWork@http://localhost:3000/static/js/bundle.js:142579:20\nperformUnitOfWork@http://localhost:3000/static/js/bundle.js:142551:27\nworkLoopSync@http://localhost:3000/static/js/bundle.js:142477:26\nrenderRootSync@http://localhost:3000/static/js/bundle.js:142443:11\nperformSyncWorkOnRoot@http://localhost:3000/static/js/bundle.js:142060:22\nflushSyncCallbackQueueImpl/<@http://localhost:3000/static/js/bundle.js:131313:30\nunstable_runWithPriority@http://localhost:3000/static/js/bundle.js:264607:16\nrunWithPriority$1@http://localhost:3000/static/js/bundle.js:131259:14\nflushSyncCallbackQueueImpl@http://localhost:3000/static/js/bundle.js:131308:30\nflushSyncCallbackQueue@http://localhost:3000/static/js/bundle.js:131296:7\ndiscreteUpdates$1@http://localhost:3000/static/js/bundle.js:142188:13\ndiscreteUpdates@http://localhost:3000/static/js/bundle.js:123663:16\ndispatchDiscreteEvent@http://localhost:3000/static/js/bundle.js:125845:22\nEventListener.handleEvent*addEventBubbleListener@http://localhost:3000/static/js/bundle.js:125967:14\naddTrappedEventListener@http://localhost:3000/static/js/bundle.js:128382:33\nlistenToNativeEvent@http://localhost:3000/static/js/bundle.js:128346:32\nlistenToAllSupportedEvents/<@http://localhost:3000/static/js/bundle.js:128297:32\nlistenToAllSupportedEvents@http://localhost:3000/static/js/bundle.js:128295:25\ncreateRootImpl@http://localhost:3000/static/js/bundle.js:145587:35\nReactDOMBlockingRoot@http://localhost:3000/static/js/bundle.js:145539:28\ncreateLegacyRoot@http://localhost:3000/static/js/bundle.js:145601:14\nlegacyCreateRootFromDOMContainer@http://localhost:3000/static/js/bundle.js:145678:14\nlegacyRenderSubtreeIntoContainer@http://localhost:3000/static/js/bundle.js:145703:48\nrender@http://localhost:3000/static/js/bundle.js:145799:14\n./src/index.js@http://localhost:3000/static/js/bundle.js:24781:42\noptions.factory@http://localhost:3000/static/js/bundle.js:299379:31\n__webpack_require__@http://localhost:3000/static/js/bundle.js:298760:33\n@http://localhost:3000/static/js/bundle.js:300018:56\n@http://localhost:3000/static/js/bundle.js:300020:12\n"

Refused to load the image 'blob:http://localhost:3000/1fde619c-040b-4971-ab5d-cba8a052d200' because it violates the following Content Security Policy directive: "default-src * 'self' data: 'unsafe-inline' 'unsafe-eval' *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback. Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme matches `self`'s scheme. The scheme 'blob:' must be added explicitly.

new Compressor(file, {
        quality: 0.6, // 0.6 can also be used, but its not recommended to go below.
        strict: true,
        checkOrientation: false,
        retainExif: true,
        // maxWidth: undefined,
        // maxHeight: undefined,
        minWidth: 0,
        minHeight: 0,
        // width: undefined,
        // height: undefined,
        resize: 'none',
        mimeType: '',
        convertTypes: 'image/jpg, image/jpeg,image/png,image/webp',
        // convertSize: 5000000,
        success: (compressedResult) => {
          // compressedResult has the compressed file.
          // Use the compressed file to upload the images to your server.        
          // setCompressedFile(res)
          file = compressedResult
          console.log(compressedResult);
        },
        error: (er)=>{
          console.log(er.message);
        }
      });
      
     Chrome browser Version 110.0.5481.177 (Official Build) (arm64)

**Comment by fengyuanchen** [comment]
Based on the error message, you may need to improve your Content Security Policy setting to support `blob:` URLs.
