### ISSUE TITLE
Compression not working on ios (webp)

### ISSUE THREAD

**Issue by krysowski** [fengyuanchen/compressorjs#172]
**Describe the bug**
Hi. When mimeType is set to 'image/webp' on the phone the output image has a png extension. The error occurs on ios 16.3.1. I tested on chrome and safari on iphone 11 pro

**Screenshots**
![image](https://user-images.githubusercontent.com/68065179/225593212-ff77b0ba-540e-4161-a8ab-55f8e5e1032a.png)
![123](https://user-images.githubusercontent.com/68065179/225599280-8495a8ea-b75b-4a6d-8134-53742410d650.png)

**Additional context**
I tried with different file sizes.

No problem on other android devices

**Comment by fengyuanchen** [comment]
Currently, Safari for iOS (16.4) does **NOT** support `HTMLCanvasElement.toBlob(callback, 'image/webp', quality)`.

> Reference: https://caniuse.com/mdn-api_htmlcanvaselement_toblob_type_parameter_webp
