### ISSUE TITLE
Adding the list of formats supported by compressojs in Docs

### ISSUE THREAD

**Issue by nik32** [fengyuanchen/compressorjs#175]
**Describe the bug**
When I was trying to upload '.tif'/'.tiff' files... the compressor produced an error
<img width="544" alt="image" src="https://github.com/fengyuanchen/compressorjs/assets/51018572/169a3c89-5f51-4226-91e0-6422faee0515">

**To Reproduce**
Just upload a '.tif' file

**Expected behaviour**
I thought that it will be converted to '.jpeg' as I had mentioned 'image/tif' in "convertTypes" property. 
@fengyuanchen I feel the list of file formats which are supported by this library should be mentioned in the docs somewhere... so that we make sure to not pass files such as '.tif' to the compressor itself... instead of it producing an error 
(PS: If supporting '.tif' is easily possible and feasible that would be great)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Edge
 - Version: 113

**Comment by fengyuanchen** [comment]
Here is the guide: [Image file type and format guide](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types).

**Comment by fengyuanchen** [comment]
Just add the guide link to the README.md: https://github.com/fengyuanchen/compressorjs#converttypes

**Comment by nik32** [comment]
Thanks @fengyuanchen

**Comment by nik32** [comment]
@fengyuanchen It would be great if the link could also be added to the npm page of compressorjs (this does not seem to be there - https://www.npmjs.com/package/compressorjs)

**Comment by fengyuanchen** [comment]
It will be there after the next version publishes to npm.

**Comment by nik32** [comment]
Got it!
