### ISSUE TITLE
Question: Is there a way to check if an image is portrait or landscape?

### ISSUE THREAD

**Issue by MatthewLHolden** [fengyuanchen/compressorjs#176]
Firstly, thanks for a great product. It's my go to for projects :)

I have a scenario whereby when uploading a resized image to a database, I would like to include whether the image is portrait or landscape. Does the package expose that information so that I can add it to my database?

Thanks!

**Comment by fengyuanchen** [comment]
Just load the image into an `<img>` element or the `new Image()` constructor, and check its [`naturalWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalWidth) and [`naturalHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/naturalHeight) directly.
