### ISSUE TITLE
手机端同时调用压缩方法（大概3-5张同时处理），有概率出现压缩后的图片是空白图片

### ISSUE THREAD

**Issue by bingege-global** [fengyuanchen/compressorjs#179]
**Describe the bug**
在手机端同时调用压缩方法（大概3-5张同时处理），有概率出现压缩后的图片是空白图片。空白图片的信息是 3648x2736  color: #FFF 96dpi。
问题不是必现，连续多次同时上传和压缩后一段时间出现（有概率）。

**Expected behavior**
压缩后的图片或者原图

**Screenshots**
![test (6)](https://github.com/fengyuanchen/compressorjs/assets/74502659/c5c7e772-eb71-42cf-9d05-9140d954f6c6)

**Smartphone (please complete the following information):**
 - Device: 华为mate30 Pro 
 - System: HarmonyOS 2.0.0
 - Browser UC浏览器V13.6.3.1143
**Additional context**
Compress方法做了Promise封装，在文件上传回调后调用。
```

export function compress(file, options) {
  return new Promise((rev, rej) => {
    new Compressor(file, {
      ...options,
      success(result) {
        setTimeout(() => rev(result), 500)
      },
      error(err) {
        setTimeout(() => rej(err), 500)
      },
    })
  })
}
```

**Comment by fengyuanchen** [comment]
可能是内存不足了。不推荐并发压缩，推荐逐张串联压缩。

**Comment by bingege-global** [comment]
> 可能是内存不足了。不推荐并发压缩，推荐逐张串联压缩。

发现在【华为mate30 Pro】下用QQ浏览器会出现这个问题，但是用三星就不会，且【华为mate30 Pro】在谷歌浏览器下也不会出现。怀疑是跟手机系统和浏览器有关。现在解决方案是暂时在这个机型禁用压缩。
