### ISSUE TITLE
I get a colored square instead of the image

### ISSUE THREAD

**Issue by marlboro18281** [fengyuanchen/compressorjs#180]
hello 

I am having an issue with Compressor.js. When I try to compress an image, I get a colored square instead of the image. 

![01](https://github.com/fengyuanchen/compressorjs/assets/23415863/421d7a8e-7777-422c-a4bd-8e15a0a97bc2)
![02](https://github.com/fengyuanchen/compressorjs/assets/23415863/3b4e07c1-c03f-4973-b259-239a91b57040)

**Comment by fengyuanchen** [comment]
1. The size of your image may be too large.
2. Try other modern browsers, please.
