### ISSUE TITLE
Error: The first argument must be a File or Blob object.

### ISSUE THREAD

**Issue by ankitjainOfficial** [fengyuanchen/compressorjs#19]
Hi,

I'm working on Angular 4, Ionic 3, Cordova application.

I'm getting this error when passing a File to `new ImageCompressor(file, options)`

This is my implementation:

```
window.resolveLocalFileSystemURL(path, (fileEntry) => {
      fileEntry.file((file) => {
        console.log(file)

          new ImageCompressor(file, {
            quality: 0.6,
            success: (result) => {
              console.log(result, result.size)
            },
            error: err => {
              console.log(err)
            }
          })
      })
    }, err => {
      console.log(err)
    });
```

I even tried reading this file as ArrayBuffer (`readAsArrayBuffer(file)`), which returns a blob and passing the same to ImageCompressor, but it did not help.

The console.log(file) returns me this:

```
File
end: 285885
lastModified: 1515080323747.9968
lastModifiedDate: 1515080323747.9968
localURL: "cdvfile://localhost/temporary/cdv_photo_016.jpg"
name: "cdv_photo_016.jpg"
size: 285885
start: 0
type: "image/jpeg"
```

It'll be great if you can let me know, where I'm going wrong?

Thanks,

**Comment by fengyuanchen** [comment]
Please check if your file is a standard blob object or not:

```sh
npm install is-blob -D
```

```js
const isBlob = require('is-blob');

console.log(isBlob(file));
```

> https://github.com/sindresorhus/is-blob

**Comment by ankitjainOfficial** [comment]
isBlob returns false. Should'nt the 'File' work? If not, can you suggest a work around? Thanks.

**Comment by fengyuanchen** [comment]
It is not an issue of this lib... I suggest you to ask help on Angular 4 or Ionic 3 or Cordova project, or StackOverflow.com, or Google.com.

**Comment by dominic-simplan** [comment]
For reference:
Cordova File type is not compatible with standard JS File API/Blob type.
You need to read the file contents and create a new JS File/Blob manually from the ArrayBuffer.
