### ISSUE TITLE
After compression, the image becomes larger

### ISSUE THREAD

**Issue by zanezhangzz** [fengyuanchen/compressorjs#190]
**Describe the bug**
When I try to compress this image to width 3600 and quality 0.9, the image size becomes larger

**To Reproduce**
See the attachment for the original picture
[demo.jpg.zip](https://github.com/user-attachments/files/16403959/demo.jpg.zip)

**Screenshots**
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/e026e038-7ea2-4a27-b42f-70b014ce3452">

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser: Chrome
 - Version: 127.0.6533.73

**Comment by zanezhangzz** [comment]
Original image width is 3840. If I change to 3600, should be smaller ? Right ?

**Comment by fengyuanchen** [comment]
Please read the description of the [`strict`](https://github.com/fengyuanchen/compressorjs?tab=readme-ov-file#strict) option.
