### ISSUE TITLE
Error: Failed to load the image. Only works after converting to .png

### ISSUE THREAD

**Issue by ericafwalsh** [fengyuanchen/compressorjs#193]
**Describe the bug**
Uploading a .jpg image returns the ambiguous error and alert "Failed to load the image."

I have been using this package for years and other .jpgs have been fine, but I have a batch of 20 photos taken with an iPhone 14 that all return this error. Converting these images to .png works. 

**To Reproduce**
1. Within my app as well as here: https://fengyuanchen.github.io/compressorjs/, 
2. Upload the attached photo
3. Notice the alert "Failed to load the image"

**Expected behavior**
To work as expected.

**Screenshots**
![Screenshot 2024-10-23 at 3 44 44 PM](https://github.com/user-attachments/assets/11a5587e-2142-495c-aaa4-e89a809d5d87)

Happening on various browsers, devices, etc. In my private app as well as the repo playground

![IMG_8435](https://github.com/user-attachments/assets/43ceced2-ced3-4cbf-876c-acb9ac33cc9b)

**Comment by fengyuanchen** [comment]
You can try to set the `checkOrientation` option to `false` for those JPG images.

**Comment by ericafwalsh** [comment]
That doesn't work for me. In my app as well as on the demo site. https://fengyuanchen.github.io/compressorjs/

I uncheck `checkOrientation` and the same error happens

**Comment by ericafwalsh** [comment]
This issue should not be closed

**Comment by fengyuanchen** [comment]
Where is your JPG image?

**Comment by ericafwalsh** [comment]
It is at the bottom of the original post, also attached it here. 
![IMG_8435 (1)](https://github.com/user-attachments/assets/13dfdcba-69fe-4448-8eae-64ea7d43b157)

**Comment by fengyuanchen** [comment]
Can not load the image at all.

**Comment by janet-yu99** [comment]
This issue happens to me as well. The photo below causes errors:
![Photo1](https://github.com/user-attachments/assets/ca410f03-177f-47f5-9871-81ef6081fa57)

When I convert this JPEG to JPG using a converter online, it works. The photo appears to not exist when you click the link, but if you right click and click "Save Link As" to save the image, you'll be able to open it on your device. I was able to open this on my Chrome browser and Firefox browser on Mac. It works on Safari. May be a photo issue itself, but not sure.

**Comment by chenggoi** [comment]
> This issue happens to me as well. The photo below causes errors:

<img width="758" height="949" alt="Image" src="https://github.com/user-attachments/assets/4639349e-6bec-423f-b5cd-06633c25310b" />

Actually, this image is in **HEIF format,** even though its extension is .jpeg. In most cases, HEIF images need to be converted to JPG or PNG before they can be displayed in a browser or compressed.

**Comment by fengyuanchen** [comment]
For HEIF format images, only a few browsers support it, see: https://caniuse.com/?search=HEIF
