### ISSUE TITLE
retainExif does not work when converting to webP ?

### ISSUE THREAD

**Issue by raphodn** [fengyuanchen/compressorjs#196]
### Compressor version

1.2.1

### Link to minimal reproduction

https://github.com/openfoodfacts/open-prices-frontend/blob/master/src/components/ProofInputRow.vue

### Steps to reproduce

Uploading a JPEG image with the following settings
```
Compressor.setDefaults({
  checkOrientation: true,  // default
  retainExif: true,
  mimeType: 'image/webp',
})
```

### What is expected?

A WebP image that retains EXIF

### What is actually happening?

a WebP image without EXIF

### Any additional comments?

Input & Output images visible here: https://file.io/MjyrNNP2teRR

**Comment by fengyuanchen** [comment]
Exif info only available for JPEG images.
