### ISSUE TITLE
Options can be improved

### ISSUE THREAD

**Issue by qgustavor** [fengyuanchen/compressorjs#2]
There are some issues in [the part of the code](https://github.com/xkeshi/image-compressor/blob/213e192411adeb8762e00dad43fb39fdf7b14ed2/src/index.js#L81-L87) which handles resizing:

* `options.height` is ignored when `options.width` is set;
* and images smaller than `options.height` and/or `options.height` can be either upscaled or not compressed (because the comparison in line 107);

Note that, because the comparison in line 107, seems resizing is only a method to try to make a image smaller, not a requirement. I think there should be at least a note in readme about that.

In lines 94 and 96 the format of the resulting image is the same format of the original image. So the format is a choice of the end user (it can be even a BMP image). Would be better if it was an option.

Finally, is complicated to add a size limit option? Too large files can be compressed into a lossy format ([like imgur](https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-), which converts PNGs larger than 5MB to JPEG).

**Comment by fengyuanchen** [comment]
Good issues and suggestion! We will improve them soon. Thanks.
