### ISSUE TITLE
Receiving an error when i have options.checkOrientation set and the image isn't loaded via url

### ISSUE THREAD

**Issue by Loktor** [fengyuanchen/compressorjs#21]
When i set the options to checkOrientation to false and the browser supports both URL/FileReader then the URL option is always used, even if the passed file cannot be resolved via an url, which results then in an error due to URL.createObjectURL(file) generating an Blob with an empty data.url. I think that this is not supposed to happen. If i have checkOrientation set to true, then everything works as it should.

Passed File:

```
lastModified:1492945785394
lastModifiedDate:Sun Apr 23 2017 13:09:45 GMT+0200 (W. Europe Daylight Time) {}
name:"79c628d31c50eb447a840f6e1ee9b6bb.jpg"
preview:"blob:http://localhost:5000/273d41e3-082a-4312-8109-210ee52ee4fc"
size:41563
type:"image/jpeg"
webkitRelativePath:""
```

Passed Data value generated from URL.createObjectURL(file):

`blob:http://localhost:5000/295ce5f1-d966-4ada-a9a6-38f87692e12b`

**Comment by fengyuanchen** [comment]
Same error as #19?

**Comment by Loktor** [comment]
The strange thing here is that i would expect the checkOrientation property to have not an effect like this. Since depending on how this is set the lib code behaves differently (e.q. uses a different way to deal with the passed file)

Also the doc for the compress method specifies:

@param {File|Blob} file - The target image file for compressing.

so i would have expected it to be able to handle both a blob and a file? or am i wrong here?

**Comment by fengyuanchen** [comment]
[`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) implements [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob)!

```js
console.log(Blob.isPrototypeOf(File));
// > true
```

```js
const isBlob = require('is-blob');

console.log(isBlob(file));
// > true
```

**Comment by Loktor** [comment]
Hmm, okay i think i found a solution to my problem, was in my part and not your lib. Great lib btw :D

**Comment by ryancui92** [comment]
I've met the same problem. Everything works when `checkOrientation = true`. When I set it to `false`, there is an error

![image](https://user-images.githubusercontent.com/3788103/35136626-96210060-fd1f-11e7-8d48-90fcd8b07a20.png)

I guess it may be no `data.url` on the return value of `URL.createObjectUrl`.

https://github.com/xkeshi/image-compressor/commit/aa07d5f178acfbbd80f10d2c17b7321f1ecdad2a#diff-1fdf421c05c1140f6d71444ea2b27638R105
