### ISSUE TITLE
Compress multiple images

### ISSUE THREAD

**Issue by LarsWith** [fengyuanchen/compressorjs#23]
I am compressing multiple images.

I have up to 25 images in a array.
I loop through all images then call `new ImageCompressor()` for each image. Is there any other way to compress multiple images at? I dont feel like my way is very thread safe

**Comment by grreeenn** [comment]
(for anyone that stumbles upon it)
https://github.com/fengyuanchen/compressorjs/issues/46#issuecomment-627270445
