### ISSUE TITLE
Cant change image name or convert into png image-compressor ignores options...

### ISSUE THREAD

**Issue by kiwo12345** [fengyuanchen/compressorjs#27]
I cant change image name or convert into png

I am using 

```
const imageCompressor = new ImageCompressor();

imageCompressor.compress(file, {
          mimeType: 'image/jpeg',
          quality: 0.7,
          maxWidth: 1280,
          maxHeight: 900,
          checkOrientation: true,
          mimeType: 'image/jpeg',
})
  .then((result) => {
    result.name = 'specific-name.jpg';
    // ...
  });
```

The image I am trying is a 398 × 326 .png but always retuns as png image and name doesnt get changed either..

But it works on a .jpg image, and if I try to convert  bigger .png image (1920 × 1200) it also works. Is seems really odd to me.

I have also tried `convertSize: 1,` in order to force convertion but with no luck..

Test image:

![111111111111](https://user-images.githubusercontent.com/10579811/36647356-9a83f658-1a84-11e8-8145-bf69889a9bbf.png)

**Comment by kiwo12345** [comment]
@fengyuanchen is your commit in the master branch now? I tried to run a update but didnt seem to fetch it.

Thanks

**Comment by fengyuanchen** [comment]
It is in the `develop` branch, can‘t you see it?

**Comment by kiwo12345** [comment]
@fengyuanchen sorry, what I should ask was when do you plan to merg it into master?
