### ISSUE TITLE
bug in v1.1.1 removing browser and adding unpkg is causing a not a constructor error

### ISSUE THREAD

**Issue by kiwo12345** [fengyuanchen/compressorjs#29]
In v1.1.1

I saw that you removed **"browser": "dist/image-compressor.js",**
  and added **"unpkg": "dist/image-compressor.js",**

This gives me the error
 **ImageCompressor is not a constructor** when I use it like this:

**window.ImageCompressor = require('image-compressor.js');
var imageCompressor = new ImageCompressor();**

However if I add the line **"browser": "dist/image-compressor.js",** to image-comrpressors package.json file the code works fine

I am using this package in a laravel/webpack project

**Comment by fengyuanchen** [comment]
```
window ImageCompressor = require('image-compressor.js/dist/image-compressor.js');
```
