### ISSUE TITLE
Doesn't compress in Safari 11.0.3

### ISSUE THREAD

**Issue by jaxxreal** [fengyuanchen/compressorjs#34]
Using: `"image-compressor.js": "^1.1.1"` with an [example](https://github.com/xkeshi/image-compressor#example) from README.

It works for some time, but compressed image size same to input image size.

Tests:
Safari 11.0.3 http://prntscr.com/iuardo
Chrome 65.0.3325.162 http://prntscr.com/iuarz2

**Comment by fengyuanchen** [comment]
Works fine with v1.1.2.
