### ISSUE TITLE
Note about: quality / compression setting

### ISSUE THREAD

**Issue by horst-n** [fengyuanchen/compressorjs#4]
As, in general, it is a good thing to compress images, it may be counter productive in some cases.
Compressing images before uploading is useful if the images later on are served 'as-is' by a website, for example. But it isn't, if the images are sources for creation of image variations, like with a CMF or CMS. For the later, it is best usage to upload the images, (that serve as original source for variation creation), in the best possible quality. (uncompressed!)

Why is this correct?
If you create variations, the images get loaded into memory, unpacked / uncompressed, and get compressed on save again. This makes every previuos compression useless. But it isn't only useless, it also has some disadvantages, when working with previously compressed images.

Please try and compare two images: 
 - A = uncompressed uploaded source, filesize = 2 MB (for example)
 - B = compressed uploaded same source, filesize = 1.1 MB (for example)

Workflow for both images is to create a halfsized variation, with e.g. PHP and GD-Library, save it, or save it and additionally pass it through a server side compressor, like image-optim.

Result will be:
 - A: filesize, for example, 0.6 MB
 - B: filesize, for example, 0.7 MB

Regardless if there is an extra compression tool involved or not, **the final filesize of the B-file will be always greater** then that of the A-file. Also **the visual quality of the B image is of lesser quality**, means it will have more (JPEG) artifacts.

So, when using this library for images uploaded into a CMF / CMS for later variation creation, everytime a quality setting of **1** should be used. This is highly recommended!

The strong and very useful part of the library in case of CMF / CMS is the possibilty to **resize the images before uploading**, means, they should not exceed some maximum dimensions in most cases! This helps in saving bandwidth and time for uploading the images and also in server-side saving of time and cpu- and memory-usage later on with every variation creation in the CMF / CMS!

**Comment by fengyuanchen** [comment]
Thanks for your notes.
