### ISSUE TITLE
Large Image fails with error undefined

### ISSUE THREAD

**Issue by deepak2510** [fengyuanchen/compressorjs#40]
I tried uploading an image of size 16mb and it failed with an error with message undefined.

**Comment by octatone** [comment]
Also encountering exceptions with large images.  Was testing a 50MB image from wikicommons. [This image specifically](https://commons.wikimedia.org/w/index.php?title=Category:Large_images#/media/File:01R_26_October_2010.jpg).

Out of memory:
<img width="943" alt="out-of-memory-crash" src="https://user-images.githubusercontent.com/492289/41603215-d02d165c-73dc-11e8-9e29-8ee0318c07b0.PNG">

Chrome crashes:
<img width="594" alt="aw-snap" src="https://user-images.githubusercontent.com/492289/41603231-d6b09922-73dc-11e8-9c27-7a7297b0a5e7.PNG">

**Comment by fengyuanchen** [comment]
Set the `checkOrientation` option to `false` can avoid out-of-memory crash when the image is too large.
