### ISSUE TITLE
How get original name from fromData?

### ISSUE THREAD

**Issue by arislanhaikal** [fengyuanchen/compressorjs#41]
I can get file image data
but i can't get original name image.

You can help me to get original name from image file?
I send data with formData.append('file', result, result.name);

Thank you

**Comment by fengyuanchen** [comment]
Is this a problem about the image compressor itself?

**Comment by arislanhaikal** [comment]
@fengyuanchen no, image compression work fine. But i must give image name manually.
The problem is, how i get original image name?

Because when sending image after compression, i get hashing image name.

**Comment by fengyuanchen** [comment]
Sorry, I cannot help you.
