### ISSUE TITLE
Images after compressing cannot be uploaded to Firebase

### ISSUE THREAD

**Issue by dongtanhuy** [fengyuanchen/compressorjs#48]
Hello, I have an issue with compressing images before uploading to Firebase. Firstly, my original code to upload a list of images to Firebase works (below)
```js
        const images = await FirebaseSevice.uploadMissionImage(imageFiles);
```
However, I need to compress images before uploading to improve the performance of my application, so I use this library but I cannot upload processed images to Firebase. My code uses `xkeshi/image-compressor`
```js
      const IM = new ImageCompressor();
      let processed = [];
      for (let image of imageFiles) {
        IM.compress(image)
          .then((result) => {
            console.log(result);
            processed.push(result);
          });
      }
      const images = await FirebaseSevice.uploadMissionImage(processed);
```
PS: `FirebaseSevice.uploadMissionImage()` takes a array of files as a parameter
Do you have any solution for this case?
Thanks.

**Comment by fengyuanchen** [comment]
```js
Promise.all([
  IM.compress(image1),
  IM.compress(image2),
  IM.compress(image3),
  // ...
]).then((processed) => {
  const images = await FirebaseSevice.uploadMissionImage(processed);
})
```
