### ISSUE TITLE
Multiple file compression

### ISSUE THREAD

**Issue by gozilla-paradise** [fengyuanchen/compressorjs#5]
It would be nice if the demo has multiple file compression support.

**Comment by fengyuanchen** [comment]
If you have multiple files, just compress them one by one.

**Comment by gozilla-paradise** [comment]
@fengyuanchen , I just add multiple file compression support to the demo site in the following pull request #6

**Comment by grreeenn** [comment]
(for anyone that stumbles upon it)
https://github.com/fengyuanchen/compressorjs/issues/46#issuecomment-627270445

**Comment by dummyuser127** [comment]
Hey There i want a feature that compress multiple file, can any one give me the code to compress multiple image
