### ISSUE TITLE
Small black line in picture's bottom after compression

### ISSUE THREAD

**Issue by FelipeMicali** [fengyuanchen/compressorjs#53]
I use this library to compress images to a max file size of 70kb before uploading it to AWS S3. I do it twice: one time for my main higher quality image and another time to generate a thumbnail of the same image.

In some cases, randomly and after conversion, the images comes out with a small black line in the bottom of the image. There's one example in here: https://s3-sa-east-1.amazonaws.com/carpediemxp-test-0000001/partners-pictures-thumb/5b528fc884f90700148ec69a

In most cases this does not happen, but when it does, it's really annoying, because images are the main attractions of my web service.

I suspect this may happen because of image dimensions floating point approximations while converting the image from one size to another, but I don't know how to fix this.

Is there any way to fix this problem and keep my images without those black lines?

Thanks in advance!

**Comment by fengyuanchen** [comment]
Fixed by #47
