### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by shiv-u** [fengyuanchen/compressorjs#54]
When I tried to run the node js server by importing the image-compressor , I got the following error as 
ReferenceError: window is not defined.

**Comment by Lukereonal** [comment]
got same problem here :(

**Comment by fengyuanchen** [comment]
Not support to run in node.

**Comment by Lukereonal** [comment]
`const ImageCompressor = require('image-compressor.js')`
somehow using that code solve the problem in my case
