### ISSUE TITLE
Compressing images on mobile phone browsers need much time

### ISSUE THREAD

**Issue by bigradish** [fengyuanchen/compressorjs#56]
Tested with Chrome and Firefox on an android mobile phone. The compressing need nearly 10 seconds to finish.
Thank you.

**Comment by fengyuanchen** [comment]
For big size photo, you may try to set the `checkOrientation` option to `false`.

**Comment by Heshade** [comment]
That solves the time issue, but you are not able to display the image correctly orientated, is it possible to reduce the time without losing the orientation?
