### ISSUE TITLE
[iOS]Safari: The operation is insecure

### ISSUE THREAD

**Issue by andyhuai** [fengyuanchen/compressorjs#57]
I used in iphone safari , iOS 11.2,
but throw this error, I've tried to solve this error,
I add this code to image-compressor.esm.js in line 627
```
image.setAttribute('crossOrigin', 'anonymous');
```

the error gone

**Comment by fengyuanchen** [comment]
I have not idea on this right now. Sorry~

**Comment by andyhuai** [comment]
@fengyuanchen watching it...

**Comment by squalvj** [comment]
im having same issue, why this is closed ?

**Comment by tom-spalding** [comment]
Can't use cookies/localstorage in incognito Safari.
