### ISSUE TITLE
usage clarification example request

### ISSUE THREAD

**Issue by rob-lindman** [fengyuanchen/compressorjs#6]
## I'm submitting a... request for information / example

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior

I would like to pass a dataURL png image that is base64 encoded to the compressor. the image is coming from another Canvas (specifically FabricJS).

Then I would like to see a simple output of the original and the compressed image, and the basic stats. 

The example presented here and the example presented on your web front end both appear to have additional complexity involving xhr requests, VueJS, etc. 

So I am asking for the simplest possible example without any additional features. This would probably be useful for others as well.

**Comment by fengyuanchen** [comment]
```js
canvas.toBlob((blob) => {
  new Compressor(blob, {
    success(result) {
      console.log(result); 
    },
    error(err) {
      console.log(err.message);
    },
  });
});
```
