### ISSUE TITLE
ie browser

### ISSUE THREAD

**Issue by NieZhengBing** [fengyuanchen/compressorjs#62]
1 when i use ie browser, 
2 go into page, js file error
how to support ie kernel browser

**Comment by fengyuanchen** [comment]
What's your IE version?

Note that the Compressor.js only support IE 10 and IE 11.

**Comment by NieZhengBing** [comment]
my IE version is IE 10, when i write with you example 
![grammer](https://user-images.githubusercontent.com/34534904/51373028-fd674480-1b39-11e9-908d-b44c16fa4044.png)
When i change 
 new Compressor(file, {
    quality: 0.6,
    success(result) {
to 
 new Compressor(file, {
    quality: 0.6,
    success: function(result) {
}

IE browser not show error, so may be this is  the problem, could you check it for me? but i not sure

**Comment by fengyuanchen** [comment]
The demo code is written in ES6 syntax, you need to transform it to ES5 with Babel.
