### ISSUE TITLE
convertSize not working

### ISSUE THREAD

**Issue by dignajar** [fengyuanchen/compressorjs#66]
**Describe the bug**
I'm trying to use the feature `convertSize` set in 1MB = `1000000` but is not compressing to that value.

**To Reproduce**
I'm using the demo.

**Expected behavior**
The image is not compressed to 1MB.

**Screenshots**
<img width="1164" alt="Screenshot 2019-04-21 at 13 03 11" src="https://user-images.githubusercontent.com/507352/56469151-1da6e800-6436-11e9-9f58-0e145613203c.png">

**Desktop (please complete the following information):**
 - Chrome

**Comment by fengyuanchen** [comment]
The `convertSize` option means the compressor will convert a PNG image to JPEG when the PNG image's size is greater than the `convertSize` value.
