### ISSUE TITLE
Get compressed file and axios response outside instance after execution.

### ISSUE THREAD

**Issue by ouuyeah** [fengyuanchen/compressorjs#67]
Hello, I want to know how to take the new compressed file to do something outside the instance, is it possible?
Also, if I use axios, how to get the axios response outside of the instance, that's it, thanks :)

**Comment by Roitr** [comment]
An Angular (typescript) example of encapsulating the compression in a function, and allowing to subscribe to an observable of the response:

````
public compressImage(file: File): Observable<File> {
    const emitter = new EventEmitter<File>();
    const compressor = new Compressor(file, {
      quality: 0.6,
      success(blobResult) {
        const compressedFile = new File([blobResult], file.name, { type: file.type, lastModified: Date.now() });
        emitter.emit(compressedFile);
      },
      error(err) {
        console.log(err.message);
      }
    });
    return emitter.asObservable();
  }
````

**Comment by itsalb3rt** [comment]
> An Angular (typescript) example of encapsulating the compression in a function, and allowing to subscribe to an observable of the response:
> 
> ```
> public compressImage(file: File): Observable<File> {
>     const emitter = new EventEmitter<File>();
>     const compressor = new Compressor(file, {
>       quality: 0.6,
>       success(blobResult) {
>         const compressedFile = new File([blobResult], file.name, { type: file.type, lastModified: Date.now() });
>         emitter.emit(compressedFile);
>       },
>       error(err) {
>         console.log(err.message);
>       }
>     });
>     return emitter.asObservable();
>   }
> ```

any example on vanilla js ?
