### ISSUE TITLE
[Feature request] Separate the "compress" method from the constructor

### ISSUE THREAD

**Issue by bigradish** [fengyuanchen/compressorjs#69]
I think the separation will improve the flexibility, and Eslint with common settings will not report errors.
Thanks.

**Comment by fengyuanchen** [comment]
What's the ESLint error exactly?

**Comment by bigradish** [comment]
Hi @fengyuanchen,
Thank you for replying.
Common Eslint requires that newly created instances are assigned to a variable and use this variable to do something. For example:
```
let ic = new Compressor(options)
ic.compress(file)
```
More importantly, I think, this separation can improve the fexibility of this compressor. Suppose that, there are many images to be compressed. We can create the Compressor only once, and use the compress method in a loop. This can avoid the overhead of creating the Compressor instance again and again.
Thank you.

**Comment by fengyuanchen** [comment]
Thanks for your suggestion, but I think it is fine to create a new Compressor instance for each image, just like ES6 `Promise`.

**Comment by bigradish** [comment]
@fengyuanchen , Sorry, I think this is a poor design.

**Comment by fengyuanchen** [comment]
Try to use the Compressor  with `Promise`:

```js
new Promise((resolve, reject) => {
  new Compressor(image, {
    success: resolve,
    error: reject,
  });
}).then((result) => {
  console.log('Compress success');
  var newImage = new Image();
  newImage.src = URL.createObjectURL(result);
  newImage.alt = 'Compressed image';
  document.body.appendChild(newImage);
}).catch((err) => {
  console.log('Compress error');
  window.alert(err.message);
}).finally(() => {
  console.log('Compress complete');
});
```
