### ISSUE TITLE
How to get asynchronously a compressed image

### ISSUE THREAD

**Issue by olegpopovskiy** [fengyuanchen/compressorjs#7]
I'm submitting a... request for information / example

[x] Documentation issue or request

Maybe I'm completely newbie to javascript, but could you explain, how I can asynchronously get a compressed image (File())? I have an array of source images, and I would like to get an array of compressed images. 
I don’t understand how I can wait for the callback success to finish an iteration, the iteration always ends immediately after creating the compressor instance.

**Comment by fengyuanchen** [comment]
Use [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) API:

```js
const images = [/* a set of image File or Blob object */];

Promise.all(images.map((image) => new Promise((resolve, reject) => {
  new Compressor(image, {
    success: resolve,
    error: reject,
  });
}))).then((compressedImages) => {
  console.log(compressedImages);
}).catch((error) => {
  console.log(error.message);
});
```

> A similar [example](https://github.com/fengyuanchen/compressorjs/blob/master/examples/work-with-promise.html).
