### ISSUE TITLE
mimeType set but not work with convertSize(PNGs)

### ISSUE THREAD

**Issue by weilinzung** [fengyuanchen/compressorjs#72]
**Describe the bug**
When I set `mimeType: image/png` & `convertSize: 150000` that would not keep the final result as png format.

**Screenshots**
![Screen-Shot-2019-11-01-at-10 02 55-PM](https://user-images.githubusercontent.com/7368063/68064736-ba0b4a80-fcf5-11e9-86f4-39638456029d.jpg)
![Screen-Shot-2019-11-01-at-10 03 04-PM](https://user-images.githubusercontent.com/7368063/68064738-c099c200-fcf5-11e9-9062-4a22bf6cb449.jpg)
![Screen-Shot-2019-11-01-at-10 03 10-PM](https://user-images.githubusercontent.com/7368063/68064739-c2fc1c00-fcf5-11e9-959d-5e0568f205ed.jpg)

**Comment by fengyuanchen** [comment]
The `convertSize` option was designed for converting a Big PNG image to a JPEG image. Not the other way around.
