### ISSUE TITLE
可以加个进度显示马

### ISSUE THREAD

**Issue by wxyer** [fengyuanchen/compressorjs#75]
已经用了大牛的两个图像处理包，非常好用，像compressorjs处理大文件能不能加个读条的，

**Comment by fengyuanchen** [comment]
因为这是个纯JavaScript项目，没有任何HTML、CSS，不方便加进度状态。建议你在压缩前于适当位置显示一个 Loading 状态图标，在压缩完成后隐藏该 Loading 状态图标。
