### ISSUE TITLE
Async return image result

### ISSUE THREAD

**Issue by rock288** [fengyuanchen/compressorjs#76]
const imageCompressor = await new CompressorJs(file, options);
How to get result when asynchronous. Because I use it everywhere and many files a time

**Comment by fengyuanchen** [comment]
It is easy to work with Promise:

```js
const result = await new Promise((resolve, reject) => {
  new Compressor(file, {
    success: resolve,
    error: reject,
  });
});
```

> Demo: https://fengyuanchen.github.io/compressorjs/examples/work-with-promise.html

**Comment by rock288** [comment]
Thanks you

Vào Th 7, 11 thg 1, 2020 lúc 14:24 Fengyuan Chen <notifications@github.com>
đã viết:
