### ISSUE TITLE
TypeError: compressorjs_1.default is not a constructor

### ISSUE THREAD

**Issue by saps31** [fengyuanchen/compressorjs#77]
I am getting this error on the latest version. If I update "export = Compressor" instead of "export default Compressor" in the index.d.ts, error is gone. Am I doing it correct ? Also please update the type definition file.

**Comment by andrew-cogesic** [comment]
Use the following import:

`const Compressor = require('compressorjs');`

Then:
` new Compressor(blob, {
        checkOrientation: false,
        maxHeight: CROP_MAX_DIM,
        .....
`
