### ISSUE TITLE
GIF images are unexpectedly converted to PNG

### ISSUE THREAD

**Issue by Arkshine** [fengyuanchen/compressorjs#78]
**Describe the bug**
GIF image are converted to PNG and there is no documentation/setting about this behavior.

**To Reproduce**
Compress a GIF image.

**Expected behavior**
A compressed GIF image.

**Screenshots**
Before compression:
![image](https://user-images.githubusercontent.com/360640/73017813-b84ab200-3e20-11ea-9bbd-6e933496cfca.png)

After compression:
![image](https://user-images.githubusercontent.com/360640/73017862-c7316480-3e20-11ea-8f64-5e9cba4c9f6c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version: 79

**Additional context**
Code used:
```JS
new Compressor(file, {
  quality: 0.6,
  strict: true,
  mimeType: 'auto',
  checkOrientation: true,
  maxWidth: 1000,
  maxHeight: 1000,
  convertSize: 'Infinity',
  success(result) {
    console.log('before', file)
    console.log('after', result)
    //
  },
})
```

**Comment by pdt590** [comment]
+1 
I have same issue

**Comment by fengyuanchen** [comment]
Just set the `mimeType` option to `image/gif` or any other types.

**Comment by pdt590** [comment]
@fengyuanchen 
I checked on https://fengyuanchen.github.io/compressorjs/ but it did not work

![image](https://user-images.githubusercontent.com/25820048/75138306-2ddcc300-56ea-11ea-8369-fb6612f5befd.png)

**Comment by fengyuanchen** [comment]
Okey. It seems the `image/gif` type is not supported by the browser.

> If the requested type is not `image/png`, but the returned value starts with `data:image/png`, then the requested type is not supported.
> From https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

**Comment by DmitryEfimenko** [comment]
what does it mean for us?
I'd think that if the compress.js can't handle a particular file format, then it should not modify the file type and just return the file as is

**Comment by mohammad5055** [comment]
Have there been any updates on this?
@fengyuanchen

**Comment by alanhe421** [comment]
So I think it's better to just go back to the original file, at least if you don't exceed the size limit, etc., and trigger the type conversion.

**Comment by fengyuanchen** [comment]
> what does it mean for us? I'd think that if the compress.js can't handle a particular file format, then it should not modify the file type and just return the file as is

It means: **DON'T compress GIF images with Compressor.js as it does not support it.**
