### ISSUE TITLE
how to upload after compressed image to root folder and server....plz share need breifly,bcoz im beginner....your work is awesome

### ISSUE THREAD

**Issue by mangaleswari6666** [fengyuanchen/compressorjs#85]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mangaleswari6666** [comment]
i cant upload,how to import axios,where i paste axios code plz help me

**Comment by fengyuanchen** [comment]
You can import the dependencies into the browser directly:

```html
<script src="https://unpkg.com/axios@0.19.2/dist/axios.min.js"></script>
<script src="https://unpkg.com/compressorjs@1.0.6/dist/compressor.min.js"></script>
```
