### ISSUE TITLE
How to Compress base64 image urls

### ISSUE THREAD

**Issue by guddumodok** [fengyuanchen/compressorjs#86]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anrananran** [comment]
just transform base64 image to a Blob, the code below can be found by Google:
```javascript
function dataURLtoFile(dataurl, filename) { // base64转file对象
  // 将base64图片转成file对象
  const arr = dataurl.split(',')
  const mime = arr[0].match(/:(.*?);/)[1]
  const bstr = atob(arr[1])
  let n = bstr.length
  const u8arr = new Uint8Array(n)

  while (n--) {
    u8arr[n] = bstr.charCodeAt(n)
  }
  return new File([u8arr], filename, { type: mime })
}
```

**Comment by mangaleswari6666** [comment]
`window.addEventListener('DOMContentLoaded', function() {
    var Vue = window.Vue;
    var URL = window.URL || window.webkitURL;
    var XMLHttpRequest = window.XMLHttpRequest;
    var Compressor = window.Compressor;

    new Vue({
        el: '#app',

        data: function() {
            var vm = this;

            return {
                options: {
                    strict: true,
                    checkOrientation: true,
                    maxWidth: undefined,
                    maxHeight: undefined,
                    minWidth: 0,
                    minHeight: 0,
                    width: undefined,
                    height: undefined,
                    quality: 0.8,
                    mimeType: '',
                    convertSize: 5000000,
                    success: function(result) {
                        console.log('Output: ', result);

                        if (URL) {
                            vm.outputURL = URL.createObjectURL(result);
                        }

                        vm.output = result;
                        vm.$refs.input.value = '';
                    },
                    error: function(err) {
                        window.alert(err.message);
                    },
                },
                inputURL: '',
                outputURL: '',
                input: {},
                output: {},
            };
        },

        filters: {
            prettySize: function(size) {
                var kilobyte = 1024;
                var megabyte = kilobyte * kilobyte;

                if (size > megabyte) {
                    return (size / megabyte).toFixed(2) + ' MB';
                } else if (size > kilobyte) {
                    return (size / kilobyte).toFixed(2) + ' KB';
                } else if (size >= 0) {
                    return size + ' B';
                }

                return 'N/A';
            },
        },

        methods: {
            compress: function(file) {
                if (!file) {
                    return;
                }

                console.log('Input: ', file);

                if (URL) {
                    this.inputURL = URL.createObjectURL(file);
                }

                this.input = file;
                new Compressor(file, this.options);
            },

            change: function(e) {
                this.compress(e.target.files ? e.target.files[0] : null);
            },

            dragover: function(e) {
                e.preventDefault();
            },

            drop: function(e) {
                e.preventDefault();
                this.compress(e.dataTransfer.files ? e.dataTransfer.files[0] : null);
            },
        },

        watch: {
            options: {
                deep: true,
                handler: function() {
                    this.compress(this.input);
                },
            },
        },

        mounted: function() {
            if (!XMLHttpRequest) {
                return;
            }

            var vm = this;
            var xhr = new XMLHttpRequest();

            xhr.onload = function() {
                var blob = xhr.response;
                var date = new Date();

                blob.lastModified = date.getTime();
                blob.lastModifiedDate = date;
                blob.name = 'picture.jpg';
                vm.compress(blob);
            };
            xhr.open('GET', 'images/picture.jpg');
            xhr.responseType = 'blob';
            xhr.send();
        },
    });
});


function sendFile(file) {
    const uri = "/index.php";
    const xhr = new XMLHttpRequest();
    const fd = new FormData();

    xhr.open("POST", uri, true);
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4 && xhr.status == 200) {
            alert(xhr.responseText); // handle response.
        }
    };
    fd.append('myFile', result, result.name, file);
    // Initiate a multipart/form-data upload
    xhr.send(fd);
}

Anyone help for upload & compressed images getting blob url,how to upload and reuse`

**Comment by mangaleswari6666** [comment]
> just transform base64 image to a Blob, the code below can be found by Google:
> 
> ```js
> function dataURLtoFile(dataurl, filename) {
>   const arr = dataurl.split(',')
>   const mime = arr[0].match(/:(.*?);/)[1]
>   const bstr = atob(arr[1])
>   let n = bstr.length
>   const u8arr = new Uint8Array(n)
> 
>   while (n--) {
>     u8arr[n] = bstr.charCodeAt(n)
>   }
>   return new File([u8arr], filename, { type: mime })
> }
> ```

Thankyou dear sir/madam......actually iam facing uploading issue,bcoz of im new for js, after compressed images comming with blob url,so i dont know how to upload.......plz do support

**Comment by mangaleswari6666** [comment]
`window.addEventListener('DOMContentLoaded', function() {
var Vue = window.Vue;
var URL = window.URL || window.webkitURL;
var XMLHttpRequest = window.XMLHttpRequest;
var Compressor = window.Compressor;

new Vue({
    el: '#app',

    data: function() {
        var vm = this;

        return {
            options: {
                strict: true,
                checkOrientation: true,
                maxWidth: undefined,
                maxHeight: undefined,
                minWidth: 0,
                minHeight: 0,
                width: undefined,
                height: undefined,
                quality: 0.8,
                mimeType: '',
                convertSize: 5000000,
                success: function(result) {
                    console.log('Output: ', result);

                    if (URL) {
                        vm.outputURL = URL.createObjectURL(result);
                    }

                    vm.output = result;
                    vm.$refs.input.value = '';
                },
                error: function(err) {
                    window.alert(err.message);
                },
            },
            inputURL: '',
            outputURL: '',
            input: {},
            output: {},
        };
    },

    filters: {
        prettySize: function(size) {
            var kilobyte = 1024;
            var megabyte = kilobyte * kilobyte;

            if (size > megabyte) {
                return (size / megabyte).toFixed(2) + ' MB';
            } else if (size > kilobyte) {
                return (size / kilobyte).toFixed(2) + ' KB';
            } else if (size >= 0) {
                return size + ' B';
            }

            return 'N/A';
        },
    },

    methods: {
        compress: function(file) {
            if (!file) {
                return;
            }

            console.log('Input: ', file);

            if (URL) {
                this.inputURL = URL.createObjectURL(file);
            }

            this.input = file;
            new Compressor(file, this.options);
        },

        change: function(e) {
            this.compress(e.target.files ? e.target.files[0] : null);
        },

        dragover: function(e) {
            e.preventDefault();
        },

        drop: function(e) {
            e.preventDefault();
            this.compress(e.dataTransfer.files ? e.dataTransfer.files[0] : null);
        },
    },

    watch: {
        options: {
            deep: true,
            handler: function() {
                this.compress(this.input);
            },
        },
    },

    mounted: function() {
        if (!XMLHttpRequest) {
            return;
        }

        var vm = this;
        var xhr = new XMLHttpRequest();

        xhr.onload = function() {
            var blob = xhr.response;
            var date = new Date();

            blob.lastModified = date.getTime();
            blob.lastModifiedDate = date;
            blob.name = 'picture.jpg';
            vm.compress(blob);
        };
        xhr.open('GET', 'images/picture.jpg');
        xhr.responseType = 'blob';
        xhr.send();
    },
});
});

function sendFile(file) {
const uri = "/index.php";
const xhr = new XMLHttpRequest();
const fd = new FormData();

xhr.open("POST", uri, true);
xhr.onreadystatechange = function() {
    if (xhr.readyState == 4 && xhr.status == 200) {
        alert(xhr.responseText); // handle response.
    }
};
fd.append('myFile', result, result.name, file);
// Initiate a multipart/form-data upload
xhr.send(fd);
}

Anyone help for upload & compressed images getting blob url,how to upload and reuse`

**Comment by fengyuanchen** [comment]
For questions about how to upload the image on the browser with JavaScript, I will suggest you ask for help on StackOverflow.com.
