### ISSUE TITLE
delay in compression and size differ from Playground

### ISSUE THREAD

**Issue by satish666** [fengyuanchen/compressorjs#87]
I am using angular 9 for front side.
My Questions are 
1. There is a little long delay when image get compressed.But at playground it is instantly.
I get blob instantly but image rendering takes time 
2. At playground image size is exact but for me it is slightly big.

**Comment by satish666** [comment]
1st question is solved Angular Error 
But please help in 2nd

**Comment by fengyuanchen** [comment]
The compressed image's size is too big? Just set the `quality` option` to a small number as `0.1`.

**Comment by nicolasplace2swap** [comment]
I have issues too with the resizing. On the playground, if i set the maxHeight/maxWidth it's working. But on my project, following the doc and based on the playground source code, it's not working at all, the output img keep it original size.
It's more like the options are totally ignored by the compressor except the quality

**Comment by ndanvers** [comment]
Bumping Nicolas' message - 
I have been using the online CompressorJS Demo you have hosted and it works fantastically - however when I am attempting to use it on my local I cannot resize the images resoluton.

To second @nicolasplace2swap message, the quality and downsampling is working well - however every option I input other than quality seems to be getting ignored.

**Comment by fengyuanchen** [comment]
@ndanvers You may need to set the `strict` option to `false`.
