### ISSUE TITLE
Losing exif headers after compressing

### ISSUE THREAD

**Issue by tmishutin** [fengyuanchen/compressorjs#88]
**Is your feature request related to a problem? Please describe.**
Currently after compressing image, EXIF rotate header is removed. This way it's not possible to do server rotate.

**Describe the solution you'd like**
Hold EXIF headers from original image and add them to compressed one.

**Describe alternatives you've considered**
Currently we are required to use compressorjs exif rotation, but for big images it's not gonna work smooth.

**Comment by fengyuanchen** [comment]
When setting the `checkOrientation` option to `true`, you will get a normalized image, it means you don't need to rotate it in the server-side again.

**Comment by tmishutin** [comment]
@fengyuanchen thank's for your reply. See, the problem is that checkOrientation may be unstable on old mobile devices, especially with big images. So to prevent memory leaks it would be nice to use server side rotation.

**Comment by fengyuanchen** [comment]
1. Set the `checkOrientation` option to `false`.
2. Set the following CSS style to the target image:
```css
img {
  image-orientation: none;
}
```

> https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation
