### ISSUE TITLE
hi, i'm i have a problem when trying to access the object like > compressor.result

### ISSUE THREAD

**Issue by jensysantana** [fengyuanchen/compressorjs#89]
hi, i'm i have a problem when trying to access the object like > compressor.result

i'm using this approach.
const compressor = new Compressor(file, {quality: 0.6, mimeType: 'image/jpeg',});
if i console.log(compressor) i have the result object but if i try to console.log(compressor.result) i having null.

other question. have some method to return file and not blob?
![Screenshot (70)](https://user-images.githubusercontent.com/36571423/82915825-40f86c80-9f3f-11ea-84ab-74096f24bde9.png)

**Comment by fengyuanchen** [comment]
The compressing process is **asynchronous**, so you should access the `result` within the `success` handler/callback!

```js
new Compressor(file, {
    quality: 0.6,
    success(result) {
      console.log(result);
    },
    error(err) {
      console.log(err.message);
    },
  });
```
