### ISSUE TITLE
Set mimeType to image/webp

### ISSUE THREAD

**Issue by Ahmedelforjani** [fengyuanchen/compressorjs#90]
When set mimeType option to image/webp it works fine when using google chrome, but in firefox the image type changes to png and the size of the compressed image become larger then the original

**Comment by fengyuanchen** [comment]
Does your Firefox browser support the [WebP image format](https://caniuse.com/#search=webp)?

**Comment by Ahmedelforjani** [comment]
yeah its supported, i have the last update

**Comment by fengyuanchen** [comment]
It means that the latest Firefox (78 currently) still does not support to use `image/webp` in the [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob).
