### ISSUE TITLE
Silent failure to compress

### ISSUE THREAD

**Issue by tejohnso** [fengyuanchen/compressorjs#91]
From what I can tell [this](https://github.com/fengyuanchen/compressorjs/blob/5c873ddf9c9d68ad088c474cd9a367e2488d9d11/src/index.js#L267) will silently fail to compress on Safari and [most](https://caniuse.com/#feat=mdn-api_htmlcanvaselement_toblob_image_quality) mobile browsers. Would it make sense to add a check for support and if not supported, fall back to the `toDataURL` option?

**Comment by fengyuanchen** [comment]
How to check if the browser supports the image quality parameter?

**Comment by fengyuanchen** [comment]
The library has imported the [`blueimp-canvas-to-blob`](https://github.com/blueimp/JavaScript-Canvas-to-Blob) library as a polyfill of `canvas.toBlob`.
