### ISSUE TITLE
Why is compression asynchronous?

### ISSUE THREAD

**Issue by SaebAmini** [fengyuanchen/compressorjs#96]
This is more of a question rather than a feature/bug report. The API having an asynchronous is a bit confusing to me, as far as it seems the compression is happening within the browser, and is a CPU-bound operation, so where does the benefit of it being asynchronous come from? is it utilizing worker threads and handing off the work to another thread?

**Comment by fengyuanchen** [comment]
Just because the [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API is asynchronous.
