### ISSUE TITLE
Randomly throws a RangeError: Maximum Call Stack Size Exceeded on some images

### ISSUE THREAD

**Issue by ryangriggs** [fengyuanchen/compressorjs#99]
When compressing images captured with mobile device camera, this error is thrown sporadically.  Note that it seems to make a difference whether the image is highly detailed or not.  Tested on multiple devices, all images taken at same resolution on the device.
Android 10, Chrome 85.0.4183.81  4000x3000 resolution
iPhone 6S, Safari 13

**Comment by fengyuanchen** [comment]
Just test the image on the official website, and if it works fine, then it may be the problem of your own code.

PS: Set the [`maxWidth/Height`](https://github.com/fengyuanchen/compressorjs#maxwidth) option if necessary.

**Comment by fengyuanchen** [comment]
> **Know iOS Resource Limits**
Your webpage performing well on the desktop is no guarantee that it will perform well on iOS. Keep in mind that iOS uses EDGE (lower bandwidth, higher latency), 4G (higher bandwidth, higher latency), and Wi-Fi (higher bandwidth, lower latency) to connect to the Internet. Therefore, you need to minimize the size of your webpage. Including unused or unnecessary images, CSS, and JavaScript in your webpages adversely affects your site’s performance on iOS.

> You also need to size images appropriately. Don’t rely on browser scaling. For example, don’t put a 100 x 100 image in a 10 x 10 <img> element. Tile small backgrounds images; don’t use large background images.

> From: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingContentforSafarioniPhone/CreatingContentforSafarioniPhone.html
